// -*- coding: utf-8 -*-
/**
 * Learn Korean - Hangul consonant / vowel / word / stage data
 */
const JAMO_SPEAK = {
  // Consonants: letter names (기역, 니은, …)
  "\u3131": "\uAE30\uC5ED",
  "\u3134": "\uB2C8\uC740",
  "\u3137": "\uB514\uADFF",
  "\u3139": "\uB9AC\uC744",
  "\u3141": "\uBBF8\uC74C",
  "\u3142": "\uBE44\uC74D",
  "\u3145": "\uC2DC\uC637",
  "\u3147": "\uC774\uC751",
  // 읒·읔 등 옛 한글 음절은 TTS 미지원 → 읃/윽/읍 등으로 대체
  "\u3148": "\uC9C0\uC743",
  "\u314A": "\uCE58\uC743",
  "\u314B": "\uD0A4\uC73D",
  "\u314C": "\uD2F0\uC73D",
  "\u314D": "\uD53C\uC74D",
  "\u314E": "\uD788\uC743",
  "\u3132": "\uC30D\uAE30\uC5ED",
  "\u3138": "\uC30D\uB514\uADFF",
  "\u3143": "\uC30D\uBE44\uC74D",
  "\u3146": "\uC30D\uC2DC\uC637",
  "\u3149": "\uC30D\uC9C0\uC743",
  // Vowels: vowel sounds (아, 어, …)
  "\u314F": "\uC544",
  "\u3151": "\uC57C",
  "\u3153": "\uC5B4",
  "\u3155": "\uC5EC",
  "\u3157": "\uC624",
  "\u315B": "\uC694",
  "\u315C": "\uC6B0",
  "\u3160": "\uC720",
  "\u3161": "\uC73C",
  "\u3163": "\uC774",
  "\u3150": "\uC560",
  "\u3152": "\uC600",
  "\u3154": "\uC5D0",
  "\u3156": "\uC608",
  "\u3158": "\uC654",
  "\u3159": "\uC648",
  "\u315A": "\uC678",
  "\u315D": "\uC6CC",
  "\u315E": "\uC6E8",
  "\u315F": "\uC704",
  "\u3162": "\uC758",
};

const HangulData = {
  vowels: [
    { id: "v_a", char: "\u314F", roman: "a", sound: "Like 'a' in father" },
    { id: "v_ya", char: "\u3151", roman: "ya", sound: "Like 'ya' in yard" },
    { id: "v_eo", char: "\u3153", roman: "eo", sound: "Like 'u' in fun" },
    { id: "v_yeo", char: "\u3155", roman: "yeo", sound: "Like 'yu' in yummy" },
    { id: "v_o", char: "\u3157", roman: "o", sound: "Like 'o' in go" },
    { id: "v_yo", char: "\u315B", roman: "yo", sound: "Like 'yo' in yoga" },
    { id: "v_u", char: "\u315C", roman: "u", sound: "Like 'oo' in food" },
    { id: "v_yu", char: "\u3160", roman: "yu", sound: "Like 'you'" },
    {
      id: "v_eu",
      char: "\u3161",
      roman: "eu",
      sound: "Like 'u' in put (no lip rounding)",
    },
    { id: "v_i", char: "\u3163", roman: "i", sound: "Like 'ee' in see" },
  ],

  compound_vowels: [
    { id: "cv_ae", char: "\u3150", roman: "ae", sound: "Like 'a' in bed" },
    {
      id: "cv_yae",
      char: "\u3152",
      roman: "yae",
      sound: "Like 'ye' in yes (short)",
    },
    { id: "cv_e", char: "\u3154", roman: "e", sound: "Like 'e' in bed" },
    { id: "cv_ye", char: "\u3156", roman: "ye", sound: "Like 'ye' in yes" },
    { id: "cv_wa", char: "\u3158", roman: "wa", sound: "Like 'wa' in water" },
    { id: "cv_wae", char: "\u3159", roman: "wae", sound: "Like 'we' in web" },
    { id: "cv_oe", char: "\u315A", roman: "oe", sound: "Like 'we' in web" },
    { id: "cv_wo", char: "\u315D", roman: "wo", sound: "Like 'wo' in wonder" },
    { id: "cv_we", char: "\u315E", roman: "we", sound: "Like 'we' in web" },
    { id: "cv_wi", char: "\u315F", roman: "wi", sound: "Like 'we' in week" },
    {
      id: "cv_ui",
      char: "\u3162",
      roman: "ui",
      sound: "Like 'ui' (eu+i combined)",
    },
  ],

  consonants: [
    {
      id: "c_g",
      char: "\u3131",
      roman: "g/k",
      sound: "Like 'g' in go (start) or 'k' (end)",
    },
    { id: "c_n", char: "\u3134", roman: "n", sound: "Like 'n' in no" },
    {
      id: "c_d",
      char: "\u3137",
      roman: "d/t",
      sound: "Like 'd' in do (start) or 't' (end)",
    },
    { id: "c_r", char: "\u3139", roman: "r/l", sound: "Between 'r' and 'l'" },
    { id: "c_m", char: "\u3141", roman: "m", sound: "Like 'm' in mom" },
    {
      id: "c_b",
      char: "\u3142",
      roman: "b/p",
      sound: "Like 'b' in boy (start) or 'p' (end)",
    },
    { id: "c_s", char: "\u3145", roman: "s", sound: "Like 's' in sun" },
    {
      id: "c_ng",
      char: "\u3147",
      roman: "-/ng",
      sound: "Silent (start) or 'ng' in sing (end)",
    },
    { id: "c_j", char: "\u3148", roman: "j", sound: "Like 'j' in joy" },
    { id: "c_ch", char: "\u314A", roman: "ch", sound: "Like 'ch' in church" },
    {
      id: "c_k",
      char: "\u314B",
      roman: "k",
      sound: "Like 'k' in key (aspirated)",
    },
    {
      id: "c_t",
      char: "\u314C",
      roman: "t",
      sound: "Like 't' in top (aspirated)",
    },
    {
      id: "c_p",
      char: "\u314D",
      roman: "p",
      sound: "Like 'p' in pot (aspirated)",
    },
    { id: "c_h", char: "\u314E", roman: "h", sound: "Like 'h' in hat" },
    {
      id: "c_gg",
      char: "\u3132",
      roman: "kk",
      sound: "Tense 'k' (no puff of air)",
    },
    {
      id: "c_dd",
      char: "\u3138",
      roman: "tt",
      sound: "Tense 't' (no puff of air)",
    },
    {
      id: "c_bb",
      char: "\u3143",
      roman: "pp",
      sound: "Tense 'p' (no puff of air)",
    },
    {
      id: "c_ss",
      char: "\u3146",
      roman: "ss",
      sound: "Tense 's' (stronger hiss)",
    },
    {
      id: "c_jj",
      char: "\u3149",
      roman: "jj",
      sound: "Tense 'j' (no puff of air)",
    },
  ],

  words: [
    { id: "w_mom", char: "엄마", roman: "eomma", meaning: "Mom / Mother" },
    { id: "w_dad", char: "아빠", roman: "appa", meaning: "Dad / Father" },
    { id: "w_water", char: "물", roman: "mul", meaning: "Water" },
    { id: "w_rice", char: "밥", roman: "bap", meaning: "Rice / Meal" },
    { id: "w_home", char: "집", roman: "jip", meaning: "Home / House" },
    { id: "w_school", char: "학교", roman: "hakgyo", meaning: "School" },
    { id: "w_friend", char: "친구", roman: "chingu", meaning: "Friend" },
    { id: "w_love", char: "사랑", roman: "sarang", meaning: "Love" },
    {
      id: "w_hello",
      char: "안녕하세요",
      roman: "annyeonghaseyo",
      meaning: "Hello (formal)",
    },
    {
      id: "w_thanks",
      char: "감사합니다",
      roman: "gamsahamnida",
      meaning: "Thank you (formal)",
    },
    { id: "w_yes", char: "네", roman: "ne", meaning: "Yes" },
    { id: "w_no", char: "아니요", roman: "aniyo", meaning: "No" },
    { id: "w_food", char: "음식", roman: "eumsik", meaning: "Food" },
    { id: "w_person", char: "사람", roman: "saram", meaning: "Person" },
    { id: "w_today", char: "오늘", roman: "oneul", meaning: "Today" },
    {
      id: "w_korean",
      char: "한국어",
      roman: "hangugeo",
      meaning: "Korean language",
    },
    { id: "w_what", char: "뭐", roman: "mwo", meaning: "What" },
    { id: "w_where", char: "어디", roman: "eodi", meaning: "Where" },
    { id: "w_when", char: "언제", roman: "eonje", meaning: "When" },
    { id: "w_how", char: "어떻게", roman: "eotteoke", meaning: "How" },
    { id: "w_name", char: "이름", roman: "ireum", meaning: "Name" },
    { id: "w_time", char: "시간", roman: "sigan", meaning: "Time" },
    { id: "w_money", char: "돈", roman: "don", meaning: "Money" },
    { id: "w_book", char: "책", roman: "chaek", meaning: "Book" },
    { id: "w_phone", char: "전화", roman: "jeonhwa", meaning: "Phone" },
    { id: "w_car", char: "자동차", roman: "jadongcha", meaning: "Car" },
    { id: "w_hospital", char: "병원", roman: "byeongwon", meaning: "Hospital" },
    { id: "w_market", char: "시장", roman: "sijang", meaning: "Market" },
    { id: "w_weather", char: "날씨", roman: "nalssi", meaning: "Weather" },
    {
      id: "w_beautiful",
      char: "아름답다",
      roman: "areumdapda",
      meaning: "Beautiful",
    },
    { id: "w_family", char: "가족", roman: "gajok", meaning: "Family" },
    { id: "w_baby", char: "아기", roman: "agi", meaning: "Baby" },
    {
      id: "w_teacher",
      char: "선생님",
      roman: "seonsaengnim",
      meaning: "Teacher",
    },
    { id: "w_student", char: "학생", roman: "haksaeng", meaning: "Student" },
    { id: "w_study", char: "공부", roman: "gongbu", meaning: "Study" },
    { id: "w_work", char: "일", roman: "il", meaning: "Work / Day" },
    { id: "w_i", char: "나", roman: "na", meaning: "I / Me" },
    { id: "w_we", char: "우리", roman: "uri", meaning: "We / Our" },
    { id: "w_good", char: "좋아요", roman: "joayo", meaning: "Good / Like" },
    {
      id: "w_delicious",
      char: "맛있어요",
      roman: "masisseoyo",
      meaning: "Delicious",
    },
    { id: "w_coffee", char: "커피", roman: "keopi", meaning: "Coffee" },
    { id: "w_milk", char: "우유", roman: "uyu", meaning: "Milk" },
    { id: "w_bread", char: "빵", roman: "ppang", meaning: "Bread" },
    { id: "w_meat", char: "고기", roman: "gogi", meaning: "Meat" },
    { id: "w_fruit", char: "과일", roman: "gwail", meaning: "Fruit" },
    { id: "w_apple", char: "사과", roman: "sagwa", meaning: "Apple" },
    { id: "w_tree", char: "나무", roman: "namu", meaning: "Tree" },
    { id: "w_flower", char: "꽃", roman: "kkot", meaning: "Flower" },
    { id: "w_river", char: "강", roman: "gang", meaning: "River" },
    { id: "w_sea", char: "바다", roman: "bada", meaning: "Sea" },
    { id: "w_mountain", char: "산", roman: "san", meaning: "Mountain" },
    { id: "w_city", char: "도시", roman: "dosi", meaning: "City" },
    { id: "w_country", char: "나라", roman: "nara", meaning: "Country" },
    { id: "w_korea", char: "한국", roman: "hanguk", meaning: "Korea" },
    { id: "w_travel", char: "여행", roman: "yeohaeng", meaning: "Travel" },
    { id: "w_movie", char: "영화", roman: "yeonghwa", meaning: "Movie" },
    { id: "w_dog", char: "개", roman: "gae", meaning: "Dog" },
    { id: "w_cat", char: "고양이", roman: "goyangi", meaning: "Cat" },
    { id: "w_sorry", char: "미안해요", roman: "mianhaeyo", meaning: "Sorry" },
    {
      id: "w_goodbye",
      char: "안녕히 가세요",
      roman: "annyeonghi gaseyo",
      meaning: "Goodbye (to someone leaving)",
    },
    { id: "w_yesterday", char: "어제", roman: "eoje", meaning: "Yesterday" },
    { id: "w_tomorrow", char: "내일", roman: "naeil", meaning: "Tomorrow" },
    { id: "w_morning", char: "아침", roman: "achim", meaning: "Morning" },
    { id: "w_evening", char: "저녁", roman: "jeonyeok", meaning: "Evening" },
    { id: "w_night", char: "밤", roman: "bam", meaning: "Night" },
    { id: "w_woman", char: "여자", roman: "yeoja", meaning: "Woman" },
    { id: "w_man", char: "남자", roman: "namja", meaning: "Man" },
    { id: "w_child", char: "아이", roman: "ai", meaning: "Child" },
    {
      id: "w_younger_sibling",
      char: "동생",
      roman: "dongsaeng",
      meaning: "Younger sibling",
    },
    {
      id: "w_grandmother",
      char: "할머니",
      roman: "halmeoni",
      meaning: "Grandmother",
    },
    {
      id: "w_grandfather",
      char: "할아버지",
      roman: "harabeoji",
      meaning: "Grandfather",
    },
    { id: "w_hand", char: "손", roman: "son", meaning: "Hand" },
    { id: "w_foot", char: "발", roman: "bal", meaning: "Foot" },
    { id: "w_face", char: "얼굴", roman: "eolgul", meaning: "Face" },
    { id: "w_ear", char: "귀", roman: "gwi", meaning: "Ear" },
    { id: "w_mouth", char: "입", roman: "ip", meaning: "Mouth" },
    { id: "w_nose", char: "코", roman: "ko", meaning: "Nose" },
    { id: "w_head", char: "머리", roman: "meori", meaning: "Head / Hair" },
    { id: "w_clothes", char: "옷", roman: "ot", meaning: "Clothes" },
    { id: "w_shoes", char: "신발", roman: "sinbal", meaning: "Shoes" },
    { id: "w_bag", char: "가방", roman: "gabang", meaning: "Bag" },
    { id: "w_door", char: "문", roman: "mun", meaning: "Door" },
    { id: "w_window", char: "창문", roman: "changmun", meaning: "Window" },
    { id: "w_bed", char: "침대", roman: "chimdae", meaning: "Bed" },
    {
      id: "w_bathroom",
      char: "화장실",
      roman: "hwajangsil",
      meaning: "Bathroom",
    },
    { id: "w_park", char: "공원", roman: "gongwon", meaning: "Park" },
    { id: "w_road", char: "길", roman: "gil", meaning: "Road / Way" },
    { id: "w_bus", char: "버스", roman: "beoseu", meaning: "Bus" },
    { id: "w_subway", char: "지하철", roman: "jihacheol", meaning: "Subway" },
    { id: "w_taxi", char: "택시", roman: "taeksi", meaning: "Taxi" },
    { id: "w_airport", char: "공항", roman: "gonghang", meaning: "Airport" },
    { id: "w_hotel", char: "호텔", roman: "hotel", meaning: "Hotel" },
    { id: "w_bank", char: "은행", roman: "eunhaeng", meaning: "Bank" },
    { id: "w_pharmacy", char: "약국", roman: "yakguk", meaning: "Pharmacy" },
    {
      id: "w_convenience_store",
      char: "편의점",
      roman: "pyeonuijeom",
      meaning: "Convenience store",
    },
    {
      id: "w_restaurant",
      char: "식당",
      roman: "sikdang",
      meaning: "Restaurant",
    },
    { id: "w_juice", char: "주스", roman: "juseu", meaning: "Juice" },
    { id: "w_tea", char: "차", roman: "cha", meaning: "Tea" },
    { id: "w_fish", char: "물고기", roman: "mulgogi", meaning: "Fish" },
    { id: "w_egg", char: "계란", roman: "gyeran", meaning: "Egg" },
    { id: "w_rain", char: "비", roman: "bi", meaning: "Rain" },
    { id: "w_snow", char: "눈", roman: "nun", meaning: "Snow" },
    { id: "w_wind", char: "바람", roman: "baram", meaning: "Wind" },
    { id: "w_sky", char: "하늘", roman: "haneul", meaning: "Sky" },
    { id: "w_ground", char: "땅", roman: "ttang", meaning: "Ground / Earth" },
    { id: "w_star", char: "별", roman: "byeol", meaning: "Star" },
    { id: "w_moon", char: "달", roman: "dal", meaning: "Moon" },
    { id: "w_one", char: "하나", roman: "hana", meaning: "One" },
    { id: "w_two", char: "둘", roman: "dul", meaning: "Two" },
    { id: "w_three", char: "셋", roman: "set", meaning: "Three" },
    { id: "w_why", char: "왜", roman: "wae", meaning: "Why" },
    { id: "w_who", char: "누구", roman: "nugu", meaning: "Who" },
    {
      id: "w_please",
      char: "주세요",
      roman: "juseyo",
      meaning: "Please give me",
    },
    {
      id: "w_okay",
      char: "괜찮아요",
      roman: "gwaenchanayo",
      meaning: "It's okay",
    },
    {
      id: "w_older_brother_m",
      char: "형",
      roman: "hyeong",
      meaning: "Older brother (male speaker)",
    },
    {
      id: "w_older_brother_f",
      char: "오빠",
      roman: "oppa",
      meaning: "Older brother (female speaker)",
    },
    {
      id: "w_older_sister_f",
      char: "언니",
      roman: "eonni",
      meaning: "Older sister (female speaker)",
    },
    {
      id: "w_older_sister_m",
      char: "누나",
      roman: "nuna",
      meaning: "Older sister (male speaker)",
    },
    { id: "w_kimchi", char: "김치", roman: "gimchi", meaning: "Kimchi" },
    { id: "w_ramen", char: "라면", roman: "ramyeon", meaning: "Ramen" },
    { id: "w_watermelon", char: "수박", roman: "subak", meaning: "Watermelon" },
    { id: "w_banana", char: "바나나", roman: "banana", meaning: "Banana" },
    { id: "w_chicken", char: "치킨", roman: "chikin", meaning: "Chicken" },
    { id: "w_salad", char: "샐러드", roman: "saelleodeu", meaning: "Salad" },
    { id: "w_sugar", char: "설탕", roman: "seoltang", meaning: "Sugar" },
    { id: "w_salt", char: "소금", roman: "sogeum", meaning: "Salt" },
    { id: "w_library", char: "도서관", roman: "doseogwan", meaning: "Library" },
    {
      id: "w_post_office",
      char: "우체국",
      roman: "ucheguk",
      meaning: "Post office",
    },
    {
      id: "w_police_station",
      char: "경찰서",
      roman: "gyeongchalseo",
      meaning: "Police station",
    },
    {
      id: "w_fire_station",
      char: "소방서",
      roman: "sobangseo",
      meaning: "Fire station",
    },
    { id: "w_company", char: "회사", roman: "hoesa", meaning: "Company / Office" },
    { id: "w_exercise", char: "운동", roman: "undong", meaning: "Exercise" },
    { id: "w_song", char: "노래", roman: "norae", meaning: "Song" },
    { id: "w_game", char: "게임", roman: "geim", meaning: "Game" },
    { id: "w_photo", char: "사진", roman: "sajin", meaning: "Photo" },
    { id: "w_computer", char: "컴퓨터", roman: "keompyuteo", meaning: "Computer" },
    { id: "w_internet", char: "인터넷", roman: "inteonet", meaning: "Internet" },
    {
      id: "w_hurt",
      char: "아파요",
      roman: "apayo",
      meaning: "It hurts / I'm sick",
    },
    { id: "w_health", char: "건강", roman: "geongang", meaning: "Health" },
    { id: "w_homework", char: "숙제", roman: "sukje", meaning: "Homework" },
    { id: "w_four", char: "넷", roman: "net", meaning: "Four" },
    { id: "w_five", char: "다섯", roman: "daseot", meaning: "Five" },
    { id: "w_six", char: "여섯", roman: "yeoseot", meaning: "Six" },
    { id: "w_seven", char: "일곱", roman: "ilgop", meaning: "Seven" },
    { id: "w_eight", char: "여덟", roman: "yeodeolp", meaning: "Eight" },
    { id: "w_nine", char: "아홉", roman: "ahop", meaning: "Nine" },
    { id: "w_ten", char: "열", roman: "yeol", meaning: "Ten" },
    { id: "w_now", char: "지금", roman: "jigeum", meaning: "Now" },
    { id: "w_monday", char: "월요일", roman: "woryoil", meaning: "Monday" },
    { id: "w_weekend", char: "주말", roman: "jumal", meaning: "Weekend" },
    { id: "w_lunch", char: "점심", roman: "jeomsim", meaning: "Lunch" },
    { id: "w_birthday", char: "생일", roman: "saengil", meaning: "Birthday" },
    { id: "w_red", char: "빨간색", roman: "ppalgansaek", meaning: "Red" },
    { id: "w_blue", char: "파란색", roman: "paransaek", meaning: "Blue" },
    { id: "w_yellow", char: "노란색", roman: "noransaek", meaning: "Yellow" },
    { id: "w_green", char: "초록색", roman: "choroksaek", meaning: "Green" },
    { id: "w_bird", char: "새", roman: "sae", meaning: "Bird" },
    { id: "w_horse", char: "말", roman: "mal", meaning: "Horse" },
    { id: "w_cow", char: "소", roman: "so", meaning: "Cow" },
    { id: "w_pig", char: "돼지", roman: "dwaeji", meaning: "Pig" },
    { id: "w_vegetable", char: "채소", roman: "chaeso", meaning: "Vegetable" },
    { id: "w_soup", char: "국", roman: "guk", meaning: "Soup" },
    { id: "w_rice_cake", char: "떡", roman: "tteok", meaning: "Rice cake" },
    {
      id: "w_ice_cream",
      char: "아이스크림",
      roman: "aiseukeurim",
      meaning: "Ice cream",
    },
    { id: "w_beer", char: "맥주", roman: "maekju", meaning: "Beer" },
    { id: "w_hat", char: "모자", roman: "moja", meaning: "Hat" },
    { id: "w_glasses", char: "안경", roman: "angyeong", meaning: "Glasses" },
    { id: "w_umbrella", char: "우산", roman: "usan", meaning: "Umbrella" },
    { id: "w_go", char: "가요", roman: "gayo", meaning: "Let's go / I go" },
    { id: "w_come", char: "와요", roman: "wayo", meaning: "Come" },
    {
      id: "w_help_please",
      char: "도와주세요",
      roman: "dowajuseyo",
      meaning: "Please help me",
    },
    {
      id: "w_congrats",
      char: "축하해요",
      roman: "chukahaeyo",
      meaning: "Congratulations",
    },
    {
      id: "w_nice_to_meet",
      char: "반가워요",
      roman: "bangawoyo",
      meaning: "Nice to meet you",
    },
    { id: "w_classroom", char: "교실", roman: "gyosil", meaning: "Classroom" },
    { id: "w_playground", char: "놀이터", roman: "noriteo", meaning: "Playground" },
    {
      id: "w_department_store",
      char: "백화점",
      roman: "baekhwajeom",
      meaning: "Department store",
    },
    { id: "w_pen", char: "펜", roman: "pen", meaning: "Pen" },
    { id: "w_eraser", char: "지우개", roman: "jiugae", meaning: "Eraser" },
    { id: "w_key", char: "열쇠", roman: "yeolsoe", meaning: "Key" },
    { id: "w_sleep", char: "잠", roman: "jam", meaning: "Sleep" },
    { id: "w_tuesday", char: "화요일", roman: "hwayoil", meaning: "Tuesday" },
    { id: "w_wednesday", char: "수요일", roman: "suyoil", meaning: "Wednesday" },
    { id: "w_thursday", char: "목요일", roman: "mogyoil", meaning: "Thursday" },
    { id: "w_friday", char: "금요일", roman: "geumyoil", meaning: "Friday" },
    { id: "w_saturday", char: "토요일", roman: "toyoil", meaning: "Saturday" },
    { id: "w_sunday", char: "일요일", roman: "iryoil", meaning: "Sunday" },
    {
      id: "w_youre_welcome",
      char: "천만에요",
      roman: "cheonmaneyo",
      meaning: "You're welcome",
    },
    {
      id: "w_excuse_me",
      char: "실례합니다",
      roman: "sillyehamnida",
      meaning: "Excuse me",
    },
    {
      id: "w_before_eating",
      char: "잘 먹겠습니다",
      roman: "jal meokgesseumnida",
      meaning: "Before eating (Bon appétit)",
    },
    {
      id: "w_after_eating",
      char: "잘 먹었습니다",
      roman: "jal meogeosseumnida",
      meaning: "After eating (Thank you for the meal)",
    },
    { id: "w_i_love_you", char: "사랑해요", roman: "saranghaeyo", meaning: "I love you" },
    {
      id: "w_goodbye_stay",
      char: "안녕히 계세요",
      roman: "annyeonghi gyeseyo",
      meaning: "Goodbye (to someone staying)",
    },
    { id: "w_grape", char: "포도", roman: "podo", meaning: "Grape" },
    { id: "w_strawberry", char: "딸기", roman: "ttalgi", meaning: "Strawberry" },
    { id: "w_orange", char: "오렌지", roman: "orenji", meaning: "Orange" },
    { id: "w_pizza", char: "피자", roman: "pija", meaning: "Pizza" },
    { id: "w_hamburger", char: "햄버거", roman: "haembeogeo", meaning: "Hamburger" },
    { id: "w_stew", char: "찌개", roman: "jjigae", meaning: "Stew" },
    { id: "w_medicine", char: "약", roman: "yak", meaning: "Medicine" },
    { id: "w_stomach", char: "배", roman: "bae", meaning: "Stomach / Belly" },
    { id: "w_back", char: "등", roman: "deung", meaning: "Back" },
    { id: "w_leg", char: "다리", roman: "dari", meaning: "Leg" },
    { id: "w_spring", char: "봄", roman: "bom", meaning: "Spring" },
    { id: "w_summer", char: "여름", roman: "yeoreum", meaning: "Summer" },
    { id: "w_autumn", char: "가을", roman: "gaeul", meaning: "Autumn" },
    { id: "w_winter", char: "겨울", roman: "gyeoul", meaning: "Winter" },
    { id: "w_hot", char: "더워요", roman: "deowoyo", meaning: "It's hot" },
    { id: "w_cold", char: "추워요", roman: "chuwoyo", meaning: "It's cold" },
    { id: "w_beach", char: "해변", roman: "haebyeon", meaning: "Beach" },
    { id: "w_island", char: "섬", roman: "seom", meaning: "Island" },
    { id: "w_station", char: "역", roman: "yeok", meaning: "Station" },
    { id: "w_train", char: "기차", roman: "gicha", meaning: "Train" },
    { id: "w_bicycle", char: "자전거", roman: "jajeongeo", meaning: "Bicycle" },
    { id: "w_ship", char: "선박", roman: "seonbak", meaning: "Ship" },
    { id: "w_clock", char: "시계", roman: "sigye", meaning: "Clock / Watch" },
    { id: "w_mirror", char: "거울", roman: "geoul", meaning: "Mirror" },
    { id: "w_toothbrush", char: "칫솔", roman: "chitsol", meaning: "Toothbrush" },
    { id: "w_towel", char: "수건", roman: "sugeon", meaning: "Towel" },
    { id: "w_soap", char: "비누", roman: "binu", meaning: "Soap" },
    { id: "w_order", char: "주문", roman: "jumun", meaning: "Order" },
    { id: "w_arm", char: "팔", roman: "pal", meaning: "Arm" },
    { id: "w_shoulder", char: "어깨", roman: "eokkae", meaning: "Shoulder" },
    { id: "w_knee", char: "무릎", roman: "mureup", meaning: "Knee" },
    { id: "w_finger", char: "손가락", roman: "songarak", meaning: "Finger" },
    { id: "w_tooth", char: "이빨", roman: "ippal", meaning: "Tooth" },
    { id: "w_heart", char: "심장", roman: "simjang", meaning: "Heart" },
    { id: "w_neck", char: "목", roman: "mok", meaning: "Neck / Throat" },
    { id: "w_tofu", char: "두부", roman: "dubu", meaning: "Tofu" },
    { id: "w_dumpling", char: "만두", roman: "mandu", meaning: "Dumpling" },
    { id: "w_noodles", char: "국수", roman: "guksu", meaning: "Noodles" },
    { id: "w_cheese", char: "치즈", roman: "chijeu", meaning: "Cheese" },
    { id: "w_cake", char: "케이크", roman: "keikeu", meaning: "Cake" },
    { id: "w_onion", char: "양파", roman: "yangpa", meaning: "Onion" },
    { id: "w_pepper", char: "고추", roman: "gochu", meaning: "Pepper / Chili" },
    { id: "w_black", char: "검은색", roman: "geomeunsaek", meaning: "Black" },
    { id: "w_white", char: "흰색", roman: "huinsaek", meaning: "White" },
    { id: "w_purple", char: "보라색", roman: "borasaek", meaning: "Purple" },
    { id: "w_husband", char: "남편", roman: "nampyeon", meaning: "Husband" },
    { id: "w_wife", char: "아내", roman: "anae", meaning: "Wife" },
    { id: "w_parents", char: "부모", roman: "bumo", meaning: "Parents" },
    { id: "w_week", char: "주", roman: "ju", meaning: "Week" },
    { id: "w_month", char: "월", roman: "wol", meaning: "Month" },
    { id: "w_year", char: "년", roman: "nyeon", meaning: "Year" },
    { id: "w_cafe", char: "카페", roman: "kape", meaning: "Cafe" },
    {
      id: "w_cinema",
      char: "영화관",
      roman: "yeonghwagwan",
      meaning: "Movie theater",
    },
    { id: "w_office", char: "사무실", roman: "samusil", meaning: "Office" },
    { id: "w_ticket", char: "표", roman: "pyo", meaning: "Ticket" },
    { id: "w_map", char: "지도", roman: "jido", meaning: "Map" },
    { id: "w_passport", char: "여권", roman: "yeogwon", meaning: "Passport" },
    { id: "w_rabbit", char: "토끼", roman: "tokki", meaning: "Rabbit" },
    { id: "w_bear", char: "곰", roman: "gom", meaning: "Bear" },
    { id: "w_duck", char: "오리", roman: "ori", meaning: "Duck" },
    { id: "w_eat", char: "먹어요", roman: "meogeoyo", meaning: "Eat" },
    { id: "w_drink", char: "마셔요", roman: "masyeoyo", meaning: "Drink" },
    { id: "w_read", char: "읽어요", roman: "ilgeoyo", meaning: "Read" },
    { id: "w_watch", char: "봐요", roman: "bwayo", meaning: "Watch / Look" },
    { id: "w_hungry", char: "배고파요", roman: "baegopayo", meaning: "I'm hungry" },
    { id: "w_tired", char: "피곤해요", roman: "pigonhaeyo", meaning: "I'm tired" },
    { id: "w_good_night", char: "잘 자요", roman: "jal jayo", meaning: "Good night" },
    { id: "w_airplane", char: "비행기", roman: "bihaenggi", meaning: "Airplane" },
  ],

  syllables: [
    { id: "s_ga", char: "\uAC00", roman: "ga", sound: "\u3131 + \u314F" },
    { id: "s_na", char: "\uB098", roman: "na", sound: "\u3134 + \u314F" },
    { id: "s_da", char: "\uB2E4", roman: "da", sound: "\u3137 + \u314F" },
    { id: "s_ma", char: "\uB9C8", roman: "ma", sound: "\u3141 + \u314F" },
    { id: "s_ba", char: "\uBC14", roman: "ba", sound: "\u3142 + \u314F" },
    { id: "s_sa", char: "\uC0AC", roman: "sa", sound: "\u3145 + \u314F" },
    { id: "s_a", char: "\uC544", roman: "a", sound: "\u3147 + \u314F" },
    { id: "s_ja", char: "\uC790", roman: "ja", sound: "\u3148 + \u314F" },
    { id: "s_ha", char: "\uD558", roman: "ha", sound: "\u314E + \u314F" },
    { id: "s_go", char: "\uACE0", roman: "go", sound: "\u3131 + \u3157" },
    { id: "s_no", char: "\uB178", roman: "no", sound: "\u3134 + \u3157" },
    { id: "s_o", char: "\uC624", roman: "o", sound: "\u3147 + \u3157" },
    { id: "s_gu", char: "\uAD6C", roman: "gu", sound: "\u3131 + \u315C" },
    { id: "s_mu", char: "\uBB34", roman: "mu", sound: "\u3141 + \u315C" },
    { id: "s_su", char: "\uC218", roman: "su", sound: "\u3145 + \u315C" },
  ],

  stages: [
    {
      id: 1,
      title: "Consonants I",
      type: "consonant",
      items: () => HangulData.consonants.slice(0, 7),
    },
    {
      id: 2,
      title: "Consonants II",
      type: "consonant",
      items: () => HangulData.consonants.slice(7),
    },
    { id: 3, title: "Vowels", type: "vowel", items: () => HangulData.vowels },
    {
      id: 4,
      title: "Syllables",
      type: "syllable",
      items: () => HangulData.syllables.slice(0, 10),
    },
    {
      id: 5,
      title: "Words I",
      type: "word",
      items: () => HangulData.words.slice(0, 8),
    },
    {
      id: 6,
      title: "Words II",
      type: "word",
      items: () => HangulData.words.slice(8),
    },
    {
      id: 7,
      title: "Stroke Writing",
      type: "stroke",
      items: () => HangulData.syllables.slice(0, 5),
    },
    {
      id: 8,
      title: "Final Quiz",
      type: "quiz",
      items: () => [...HangulData.syllables, ...HangulData.words.slice(0, 5)],
    },
  ],

  /** TTS text: consonants use letter names (기역), vowels use sounds (아), words as written. */
  getSpeakText(itemOrChar) {
    if (!itemOrChar) return "";
    if (typeof itemOrChar === "string") {
      return JAMO_SPEAK[itemOrChar] || itemOrChar;
    }
    if (itemOrChar.speak) return itemOrChar.speak;
    const ch = itemOrChar.char || "";
    if (!ch) return "";
    if (itemOrChar.meaning) return ch;
    return JAMO_SPEAK[ch] || ch;
  },

  getLabel(item) {
    if (!item) return "";
    if (item.meaning) return item.meaning;
    if (item.sound) return item.sound;
    return item.roman || item.char;
  },

  getHint(item) {
    if (!item) return "";
    if (item.meaning) return `${item.roman} \u00B7 ${item.meaning}`;
    if (item.sound) return `${item.roman} \u00B7 ${item.sound}`;
    return item.roman || "";
  },

  getStage(id) {
    const stage = HangulData.stages.find((s) => s.id === Number(id));
    if (!stage)
      return { ...HangulData.stages[0], items: HangulData.stages[0].items() };
    return { ...stage, items: stage.items() };
  },

  getRandomQuizOptions(correct, pool, count = 4) {
    const others = pool.filter((item) => item.char !== correct.char);
    const shuffled = [...others].sort(() => Math.random() - 0.5);
    const options = [correct, ...shuffled.slice(0, count - 1)];
    return options.sort(() => Math.random() - 0.5);
  },

  starsFromScore(score, maxScore) {
    const ratio = maxScore > 0 ? score / maxScore : 0;
    if (ratio >= 0.9) return 3;
    if (ratio >= 0.6) return 2;
    if (ratio >= 0.3) return 1;
    return 0;
  },
};

if (typeof module !== "undefined") module.exports = HangulData;
