// -*- coding: utf-8 -*-
/**
 * Learn Korean - Hangul consonant / vowel / word / stage data
 */
const JAMO_SPEAK = {
  // Consonants: letter names (기역, 니은, …)
  "\u3131": "\uAE30\uC5ED",
  "\u3134": "\uB2C8\uC740",
  "\u3137": "\uB514\uADFF",
  "\u3139": "\uB9AC\uC744",
  "\u3141": "\uBBF8\uC74C",
  "\u3142": "\uBE44\uC74D",
  "\u3145": "\uC2DC\uC637",
  "\u3147": "\uC774\uC751",
  // 읒·읔 등 옛 한글 음절은 TTS 미지원 → 읃/윽/읍 등으로 대체
  "\u3148": "\uC9C0\uC743",
  "\u314A": "\uCE58\uC743",
  "\u314B": "\uD0A4\uC73D",
  "\u314C": "\uD2F0\uC73D",
  "\u314D": "\uD53C\uC74D",
  "\u314E": "\uD788\uC743",
  "\u3132": "\uC30D\uAE30\uC5ED",
  "\u3138": "\uC30D\uB514\uADFF",
  "\u3143": "\uC30D\uBE44\uC74D",
  "\u3146": "\uC30D\uC2DC\uC637",
  "\u3149": "\uC30D\uC9C0\uC743",
  // Vowels: vowel sounds (아, 어, …)
  "\u314F": "\uC544",
  "\u3151": "\uC57C",
  "\u3153": "\uC5B4",
  "\u3155": "\uC5EC",
  "\u3157": "\uC624",
  "\u315B": "\uC694",
  "\u315C": "\uC6B0",
  "\u3160": "\uC720",
  "\u3161": "\uC73C",
  "\u3163": "\uC774",
  "\u3150": "\uC560",
  "\u3152": "\uC600",
  "\u3154": "\uC5D0",
  "\u3156": "\uC608",
  "\u3158": "\uC654",
  "\u3159": "\uC648",
  "\u315A": "\uC678",
  "\u315D": "\uC6CC",
  "\u315E": "\uC6E8",
  "\u315F": "\uC704",
  "\u3162": "\uC758",
};

const CHO_INDEX = {
  "\u3131": 0,
  "\u3132": 1,
  "\u3134": 2,
  "\u3137": 3,
  "\u3138": 4,
  "\u3139": 5,
  "\u3141": 6,
  "\u3142": 7,
  "\u3143": 8,
  "\u3145": 9,
  "\u3146": 10,
  "\u3147": 11,
  "\u3148": 12,
  "\u3149": 13,
  "\u314A": 14,
  "\u314B": 15,
  "\u314C": 16,
  "\u314D": 17,
  "\u314E": 18,
};

const JUNG_INDEX = {
  "\u314F": 0,
  "\u3150": 1,
  "\u3151": 2,
  "\u3152": 3,
  "\u3153": 4,
  "\u3154": 5,
  "\u3155": 6,
  "\u3156": 7,
  "\u3157": 8,
  "\u3158": 9,
  "\u3159": 10,
  "\u315A": 11,
  "\u315B": 12,
  "\u315C": 13,
  "\u315D": 14,
  "\u315E": 15,
  "\u315F": 16,
  "\u3160": 17,
  "\u3161": 18,
  "\u3162": 19,
  "\u3163": 20,
};

const INITIAL_ROMAN = {
  c_g: "g",
  c_n: "n",
  c_d: "d",
  c_r: "r",
  c_m: "m",
  c_b: "b",
  c_s: "s",
  c_ng: "",
  c_j: "j",
  c_ch: "ch",
  c_k: "k",
  c_t: "t",
  c_p: "p",
  c_h: "h",
  c_gg: "kk",
  c_dd: "tt",
  c_bb: "pp",
  c_ss: "ss",
  c_jj: "jj",
};

function composeSyllable(choChar, jungChar) {
  const cho = CHO_INDEX[choChar];
  const jung = JUNG_INDEX[jungChar];
  if (cho === undefined || jung === undefined) return "";
  return String.fromCharCode(0xac00 + cho * 588 + jung * 28);
}

function buildSyllableItem(consonant, vowel) {
  const char = composeSyllable(consonant.char, vowel.char);
  if (!char) return null;
  const initial = INITIAL_ROMAN[consonant.id] ?? "";
  return {
    id: `s_${consonant.id}_${vowel.id}`,
    char,
    roman: initial + vowel.roman,
    sound: `${consonant.char} + ${vowel.char}`,
  };
}

function buildAllSyllables(consonants, vowels, compoundVowels) {
  const allVowels = [...vowels, ...compoundVowels];
  const sortedConsonants = [...consonants].sort(
    (a, b) => CHO_INDEX[a.char] - CHO_INDEX[b.char],
  );
  const items = [];
  for (const consonant of sortedConsonants) {
    for (const vowel of allVowels) {
      const item = buildSyllableItem(consonant, vowel);
      if (item) items.push(item);
    }
  }
  return items;
}

function buildSyllablesGroupedByConsonant(consonants, vowels, compoundVowels) {
  const allVowels = [...vowels, ...compoundVowels];
  const sortedConsonants = [...consonants].sort(
    (a, b) => CHO_INDEX[a.char] - CHO_INDEX[b.char],
  );
  return sortedConsonants.map((consonant) => ({
    consonant,
    items: allVowels
      .map((vowel) => buildSyllableItem(consonant, vowel))
      .filter(Boolean),
  }));
}

const HangulData = {
  vowels: [
    { id: "v_a", char: "\u314F", roman: "a", sound: "Like 'a' in father" },
    { id: "v_ya", char: "\u3151", roman: "ya", sound: "Like 'ya' in yard" },
    { id: "v_eo", char: "\u3153", roman: "eo", sound: "Like 'u' in fun" },
    { id: "v_yeo", char: "\u3155", roman: "yeo", sound: "Like 'yu' in yummy" },
    { id: "v_o", char: "\u3157", roman: "o", sound: "Like 'o' in go" },
    { id: "v_yo", char: "\u315B", roman: "yo", sound: "Like 'yo' in yoga" },
    { id: "v_u", char: "\u315C", roman: "u", sound: "Like 'oo' in food" },
    { id: "v_yu", char: "\u3160", roman: "yu", sound: "Like 'you'" },
    {
      id: "v_eu",
      char: "\u3161",
      roman: "eu",
      sound: "Like 'u' in put (no lip rounding)",
    },
    { id: "v_i", char: "\u3163", roman: "i", sound: "Like 'ee' in see" },
  ],

  compound_vowels: [
    { id: "cv_ae", char: "\u3150", roman: "ae", sound: "Like 'a' in bed" },
    {
      id: "cv_yae",
      char: "\u3152",
      roman: "yae",
      sound: "Like 'ye' in yes (short)",
    },
    { id: "cv_e", char: "\u3154", roman: "e", sound: "Like 'e' in bed" },
    { id: "cv_ye", char: "\u3156", roman: "ye", sound: "Like 'ye' in yes" },
    { id: "cv_wa", char: "\u3158", roman: "wa", sound: "Like 'wa' in water" },
    { id: "cv_wae", char: "\u3159", roman: "wae", sound: "Like 'we' in web" },
    { id: "cv_oe", char: "\u315A", roman: "oe", sound: "Like 'we' in web" },
    { id: "cv_wo", char: "\u315D", roman: "wo", sound: "Like 'wo' in wonder" },
    { id: "cv_we", char: "\u315E", roman: "we", sound: "Like 'we' in web" },
    { id: "cv_wi", char: "\u315F", roman: "wi", sound: "Like 'we' in week" },
    {
      id: "cv_ui",
      char: "\u3162",
      roman: "ui",
      sound: "Like 'ui' (eu+i combined)",
    },
  ],

  consonants: [
    {
      id: "c_g",
      char: "\u3131",
      roman: "g/k",
      sound: "Like 'g' in go (start) or 'k' (end)",
    },
    { id: "c_n", char: "\u3134", roman: "n", sound: "Like 'n' in no" },
    {
      id: "c_d",
      char: "\u3137",
      roman: "d/t",
      sound: "Like 'd' in do (start) or 't' (end)",
    },
    { id: "c_r", char: "\u3139", roman: "r/l", sound: "Between 'r' and 'l'" },
    { id: "c_m", char: "\u3141", roman: "m", sound: "Like 'm' in mom" },
    {
      id: "c_b",
      char: "\u3142",
      roman: "b/p",
      sound: "Like 'b' in boy (start) or 'p' (end)",
    },
    { id: "c_s", char: "\u3145", roman: "s", sound: "Like 's' in sun" },
    {
      id: "c_ng",
      char: "\u3147",
      roman: "-/ng",
      sound: "Silent (start) or 'ng' in sing (end)",
    },
    { id: "c_j", char: "\u3148", roman: "j", sound: "Like 'j' in joy" },
    { id: "c_ch", char: "\u314A", roman: "ch", sound: "Like 'ch' in church" },
    {
      id: "c_k",
      char: "\u314B",
      roman: "k",
      sound: "Like 'k' in key (aspirated)",
    },
    {
      id: "c_t",
      char: "\u314C",
      roman: "t",
      sound: "Like 't' in top (aspirated)",
    },
    {
      id: "c_p",
      char: "\u314D",
      roman: "p",
      sound: "Like 'p' in pot (aspirated)",
    },
    { id: "c_h", char: "\u314E", roman: "h", sound: "Like 'h' in hat" },
    {
      id: "c_gg",
      char: "\u3132",
      roman: "kk",
      sound: "Tense 'k' (no puff of air)",
    },
    {
      id: "c_dd",
      char: "\u3138",
      roman: "tt",
      sound: "Tense 't' (no puff of air)",
    },
    {
      id: "c_bb",
      char: "\u3143",
      roman: "pp",
      sound: "Tense 'p' (no puff of air)",
    },
    {
      id: "c_ss",
      char: "\u3146",
      roman: "ss",
      sound: "Tense 's' (stronger hiss)",
    },
    {
      id: "c_jj",
      char: "\u3149",
      roman: "jj",
      sound: "Tense 'j' (no puff of air)",
    },
  ],

  words: [
    { id: "w_mom", char: "엄마", roman: "eomma", meaning: "Mom / Mother" },
    { id: "w_dad", char: "아빠", roman: "appa", meaning: "Dad / Father" },
    { id: "w_water", char: "물", roman: "mul", meaning: "Water" },
    { id: "w_rice", char: "밥", roman: "bap", meaning: "Rice / Meal" },
    { id: "w_home", char: "집", roman: "jip", meaning: "Home / House" },
    { id: "w_school", char: "학교", roman: "hakgyo", meaning: "School" },
    { id: "w_friend", char: "친구", roman: "chingu", meaning: "Friend" },
    { id: "w_love", char: "사랑", roman: "sarang", meaning: "Love" },
    {
      id: "w_hello",
      char: "안녕하세요",
      roman: "annyeonghaseyo",
      meaning: "Hello (formal)",
    },
    {
      id: "w_thanks",
      char: "감사합니다",
      roman: "gamsahamnida",
      meaning: "Thank you (formal)",
    },
    { id: "w_yes", char: "네", roman: "ne", meaning: "Yes" },
    { id: "w_no", char: "아니요", roman: "aniyo", meaning: "No" },
    { id: "w_food", char: "음식", roman: "eumsik", meaning: "Food" },
    { id: "w_person", char: "사람", roman: "saram", meaning: "Person" },
    { id: "w_today", char: "오늘", roman: "oneul", meaning: "Today" },
    {
      id: "w_korean",
      char: "한국어",
      roman: "hangugeo",
      meaning: "Korean language",
    },
    { id: "w_what", char: "뭐", roman: "mwo", meaning: "What" },
    { id: "w_where", char: "어디", roman: "eodi", meaning: "Where" },
    { id: "w_when", char: "언제", roman: "eonje", meaning: "When" },
    { id: "w_how", char: "어떻게", roman: "eotteoke", meaning: "How" },
    { id: "w_name", char: "이름", roman: "ireum", meaning: "Name" },
    { id: "w_time", char: "시간", roman: "sigan", meaning: "Time" },
    { id: "w_money", char: "돈", roman: "don", meaning: "Money" },
    { id: "w_book", char: "책", roman: "chaek", meaning: "Book" },
    { id: "w_phone", char: "전화", roman: "jeonhwa", meaning: "Phone" },
    { id: "w_car", char: "자동차", roman: "jadongcha", meaning: "Car" },
    { id: "w_hospital", char: "병원", roman: "byeongwon", meaning: "Hospital" },
    { id: "w_market", char: "시장", roman: "sijang", meaning: "Market" },
    { id: "w_weather", char: "날씨", roman: "nalssi", meaning: "Weather" },
    {
      id: "w_beautiful",
      char: "아름답다",
      roman: "areumdapda",
      meaning: "Beautiful",
    },
    { id: "w_family", char: "가족", roman: "gajok", meaning: "Family" },
    { id: "w_baby", char: "아기", roman: "agi", meaning: "Baby" },
    {
      id: "w_teacher",
      char: "선생님",
      roman: "seonsaengnim",
      meaning: "Teacher",
    },
    { id: "w_student", char: "학생", roman: "haksaeng", meaning: "Student" },
    { id: "w_study", char: "공부", roman: "gongbu", meaning: "Study" },
    { id: "w_work", char: "일", roman: "il", meaning: "Work / Day" },
    { id: "w_i", char: "나", roman: "na", meaning: "I / Me" },
    { id: "w_we", char: "우리", roman: "uri", meaning: "We / Our" },
    { id: "w_good", char: "좋아요", roman: "joayo", meaning: "Good / Like" },
    {
      id: "w_delicious",
      char: "맛있어요",
      roman: "masisseoyo",
      meaning: "Delicious",
    },
    { id: "w_coffee", char: "커피", roman: "keopi", meaning: "Coffee" },
    { id: "w_milk", char: "우유", roman: "uyu", meaning: "Milk" },
    { id: "w_bread", char: "빵", roman: "ppang", meaning: "Bread" },
    { id: "w_meat", char: "고기", roman: "gogi", meaning: "Meat" },
    { id: "w_fruit", char: "과일", roman: "gwail", meaning: "Fruit" },
    { id: "w_apple", char: "사과", roman: "sagwa", meaning: "Apple" },
    { id: "w_tree", char: "나무", roman: "namu", meaning: "Tree" },
    { id: "w_flower", char: "꽃", roman: "kkot", meaning: "Flower" },
    { id: "w_river", char: "강", roman: "gang", meaning: "River" },
    { id: "w_sea", char: "바다", roman: "bada", meaning: "Sea" },
    { id: "w_mountain", char: "산", roman: "san", meaning: "Mountain" },
    { id: "w_city", char: "도시", roman: "dosi", meaning: "City" },
    { id: "w_country", char: "나라", roman: "nara", meaning: "Country" },
    { id: "w_korea", char: "한국", roman: "hanguk", meaning: "Korea" },
    { id: "w_travel", char: "여행", roman: "yeohaeng", meaning: "Travel" },
    { id: "w_movie", char: "영화", roman: "yeonghwa", meaning: "Movie" },
    { id: "w_dog", char: "개", roman: "gae", meaning: "Dog" },
    { id: "w_cat", char: "고양이", roman: "goyangi", meaning: "Cat" },
    { id: "w_sorry", char: "미안해요", roman: "mianhaeyo", meaning: "Sorry" },
    {
      id: "w_goodbye",
      char: "안녕히 가세요",
      roman: "annyeonghi gaseyo",
      meaning: "Goodbye (to someone leaving)",
    },
    { id: "w_yesterday", char: "어제", roman: "eoje", meaning: "Yesterday" },
    { id: "w_tomorrow", char: "내일", roman: "naeil", meaning: "Tomorrow" },
    { id: "w_morning", char: "아침", roman: "achim", meaning: "Morning" },
    { id: "w_evening", char: "저녁", roman: "jeonyeok", meaning: "Evening" },
    { id: "w_night", char: "밤", roman: "bam", meaning: "Night" },
    { id: "w_woman", char: "여자", roman: "yeoja", meaning: "Woman" },
    { id: "w_man", char: "남자", roman: "namja", meaning: "Man" },
    { id: "w_child", char: "아이", roman: "ai", meaning: "Child" },
    {
      id: "w_younger_sibling",
      char: "동생",
      roman: "dongsaeng",
      meaning: "Younger sibling",
    },
    {
      id: "w_grandmother",
      char: "할머니",
      roman: "halmeoni",
      meaning: "Grandmother",
    },
    {
      id: "w_grandfather",
      char: "할아버지",
      roman: "harabeoji",
      meaning: "Grandfather",
    },
    { id: "w_hand", char: "손", roman: "son", meaning: "Hand" },
    { id: "w_foot", char: "발", roman: "bal", meaning: "Foot" },
    { id: "w_face", char: "얼굴", roman: "eolgul", meaning: "Face" },
    { id: "w_ear", char: "귀", roman: "gwi", meaning: "Ear" },
    { id: "w_mouth", char: "입", roman: "ip", meaning: "Mouth" },
    { id: "w_nose", char: "코", roman: "ko", meaning: "Nose" },
    { id: "w_head", char: "머리", roman: "meori", meaning: "Head / Hair" },
    { id: "w_clothes", char: "옷", roman: "ot", meaning: "Clothes" },
    { id: "w_shoes", char: "신발", roman: "sinbal", meaning: "Shoes" },
    { id: "w_bag", char: "가방", roman: "gabang", meaning: "Bag" },
    { id: "w_door", char: "문", roman: "mun", meaning: "Door" },
    { id: "w_window", char: "창문", roman: "changmun", meaning: "Window" },
    { id: "w_bed", char: "침대", roman: "chimdae", meaning: "Bed" },
    {
      id: "w_bathroom",
      char: "화장실",
      roman: "hwajangsil",
      meaning: "Bathroom",
    },
    { id: "w_park", char: "공원", roman: "gongwon", meaning: "Park" },
    { id: "w_road", char: "길", roman: "gil", meaning: "Road / Way" },
    { id: "w_bus", char: "버스", roman: "beoseu", meaning: "Bus" },
    { id: "w_subway", char: "지하철", roman: "jihacheol", meaning: "Subway" },
    { id: "w_taxi", char: "택시", roman: "taeksi", meaning: "Taxi" },
    { id: "w_airport", char: "공항", roman: "gonghang", meaning: "Airport" },
    { id: "w_hotel", char: "호텔", roman: "hotel", meaning: "Hotel" },
    { id: "w_bank", char: "은행", roman: "eunhaeng", meaning: "Bank" },
    { id: "w_pharmacy", char: "약국", roman: "yakguk", meaning: "Pharmacy" },
    {
      id: "w_convenience_store",
      char: "편의점",
      roman: "pyeonuijeom",
      meaning: "Convenience store",
    },
    {
      id: "w_restaurant",
      char: "식당",
      roman: "sikdang",
      meaning: "Restaurant",
    },
    { id: "w_juice", char: "주스", roman: "juseu", meaning: "Juice" },
    { id: "w_tea", char: "차", roman: "cha", meaning: "Tea" },
    { id: "w_fish", char: "물고기", roman: "mulgogi", meaning: "Fish" },
    { id: "w_egg", char: "계란", roman: "gyeran", meaning: "Egg" },
    { id: "w_rain", char: "비", roman: "bi", meaning: "Rain" },
    { id: "w_snow", char: "눈", roman: "nun", meaning: "Snow" },
    { id: "w_wind", char: "바람", roman: "baram", meaning: "Wind" },
    { id: "w_sky", char: "하늘", roman: "haneul", meaning: "Sky" },
    { id: "w_ground", char: "땅", roman: "ttang", meaning: "Ground / Earth" },
    { id: "w_star", char: "별", roman: "byeol", meaning: "Star" },
    { id: "w_moon", char: "달", roman: "dal", meaning: "Moon" },
    { id: "w_one", char: "하나", roman: "hana", meaning: "One" },
    { id: "w_two", char: "둘", roman: "dul", meaning: "Two" },
    { id: "w_three", char: "셋", roman: "set", meaning: "Three" },
    { id: "w_why", char: "왜", roman: "wae", meaning: "Why" },
    { id: "w_who", char: "누구", roman: "nugu", meaning: "Who" },
    {
      id: "w_please",
      char: "주세요",
      roman: "juseyo",
      meaning: "Please give me",
    },
    {
      id: "w_okay",
      char: "괜찮아요",
      roman: "gwaenchanayo",
      meaning: "It's okay",
    },
    {
      id: "w_older_brother_m",
      char: "형",
      roman: "hyeong",
      meaning: "Older brother (male speaker)",
    },
    {
      id: "w_older_brother_f",
      char: "오빠",
      roman: "oppa",
      meaning: "Older brother (female speaker)",
    },
    {
      id: "w_older_sister_f",
      char: "언니",
      roman: "eonni",
      meaning: "Older sister (female speaker)",
    },
    {
      id: "w_older_sister_m",
      char: "누나",
      roman: "nuna",
      meaning: "Older sister (male speaker)",
    },
    { id: "w_kimchi", char: "김치", roman: "gimchi", meaning: "Kimchi" },
    { id: "w_ramen", char: "라면", roman: "ramyeon", meaning: "Ramen" },
    { id: "w_watermelon", char: "수박", roman: "subak", meaning: "Watermelon" },
    { id: "w_banana", char: "바나나", roman: "banana", meaning: "Banana" },
    { id: "w_chicken", char: "치킨", roman: "chikin", meaning: "Chicken" },
    { id: "w_salad", char: "샐러드", roman: "saelleodeu", meaning: "Salad" },
    { id: "w_sugar", char: "설탕", roman: "seoltang", meaning: "Sugar" },
    { id: "w_salt", char: "소금", roman: "sogeum", meaning: "Salt" },
    { id: "w_library", char: "도서관", roman: "doseogwan", meaning: "Library" },
    {
      id: "w_post_office",
      char: "우체국",
      roman: "ucheguk",
      meaning: "Post office",
    },
    {
      id: "w_police_station",
      char: "경찰서",
      roman: "gyeongchalseo",
      meaning: "Police station",
    },
    {
      id: "w_fire_station",
      char: "소방서",
      roman: "sobangseo",
      meaning: "Fire station",
    },
    { id: "w_company", char: "회사", roman: "hoesa", meaning: "Company / Office" },
    { id: "w_exercise", char: "운동", roman: "undong", meaning: "Exercise" },
    { id: "w_song", char: "노래", roman: "norae", meaning: "Song" },
    { id: "w_game", char: "게임", roman: "geim", meaning: "Game" },
    { id: "w_photo", char: "사진", roman: "sajin", meaning: "Photo" },
    { id: "w_computer", char: "컴퓨터", roman: "keompyuteo", meaning: "Computer" },
    { id: "w_internet", char: "인터넷", roman: "inteonet", meaning: "Internet" },
    {
      id: "w_hurt",
      char: "아파요",
      roman: "apayo",
      meaning: "It hurts / I'm sick",
    },
    { id: "w_health", char: "건강", roman: "geongang", meaning: "Health" },
    { id: "w_homework", char: "숙제", roman: "sukje", meaning: "Homework" },
    { id: "w_four", char: "넷", roman: "net", meaning: "Four" },
    { id: "w_five", char: "다섯", roman: "daseot", meaning: "Five" },
    { id: "w_six", char: "여섯", roman: "yeoseot", meaning: "Six" },
    { id: "w_seven", char: "일곱", roman: "ilgop", meaning: "Seven" },
    { id: "w_eight", char: "여덟", roman: "yeodeolp", meaning: "Eight" },
    { id: "w_nine", char: "아홉", roman: "ahop", meaning: "Nine" },
    { id: "w_ten", char: "열", roman: "yeol", meaning: "Ten" },
    { id: "w_now", char: "지금", roman: "jigeum", meaning: "Now" },
    { id: "w_monday", char: "월요일", roman: "woryoil", meaning: "Monday" },
    { id: "w_weekend", char: "주말", roman: "jumal", meaning: "Weekend" },
    { id: "w_lunch", char: "점심", roman: "jeomsim", meaning: "Lunch" },
    { id: "w_birthday", char: "생일", roman: "saengil", meaning: "Birthday" },
    { id: "w_red", char: "빨간색", roman: "ppalgansaek", meaning: "Red" },
    { id: "w_blue", char: "파란색", roman: "paransaek", meaning: "Blue" },
    { id: "w_yellow", char: "노란색", roman: "noransaek", meaning: "Yellow" },
    { id: "w_green", char: "초록색", roman: "choroksaek", meaning: "Green" },
    { id: "w_bird", char: "새", roman: "sae", meaning: "Bird" },
    { id: "w_horse", char: "말", roman: "mal", meaning: "Horse" },
    { id: "w_cow", char: "소", roman: "so", meaning: "Cow" },
    { id: "w_pig", char: "돼지", roman: "dwaeji", meaning: "Pig" },
    { id: "w_vegetable", char: "채소", roman: "chaeso", meaning: "Vegetable" },
    { id: "w_soup", char: "국", roman: "guk", meaning: "Soup" },
    { id: "w_rice_cake", char: "떡", roman: "tteok", meaning: "Rice cake" },
    {
      id: "w_ice_cream",
      char: "아이스크림",
      roman: "aiseukeurim",
      meaning: "Ice cream",
    },
    { id: "w_beer", char: "맥주", roman: "maekju", meaning: "Beer" },
    { id: "w_hat", char: "모자", roman: "moja", meaning: "Hat" },
    { id: "w_glasses", char: "안경", roman: "angyeong", meaning: "Glasses" },
    { id: "w_umbrella", char: "우산", roman: "usan", meaning: "Umbrella" },
    { id: "w_go", char: "가요", roman: "gayo", meaning: "Let's go / I go" },
    { id: "w_come", char: "와요", roman: "wayo", meaning: "Come" },
    {
      id: "w_help_please",
      char: "도와주세요",
      roman: "dowajuseyo",
      meaning: "Please help me",
    },
    {
      id: "w_congrats",
      char: "축하해요",
      roman: "chukahaeyo",
      meaning: "Congratulations",
    },
    {
      id: "w_nice_to_meet",
      char: "반가워요",
      roman: "bangawoyo",
      meaning: "Nice to meet you",
    },
    { id: "w_classroom", char: "교실", roman: "gyosil", meaning: "Classroom" },
    { id: "w_playground", char: "놀이터", roman: "noriteo", meaning: "Playground" },
    {
      id: "w_department_store",
      char: "백화점",
      roman: "baekhwajeom",
      meaning: "Department store",
    },
    { id: "w_pen", char: "펜", roman: "pen", meaning: "Pen" },
    { id: "w_eraser", char: "지우개", roman: "jiugae", meaning: "Eraser" },
    { id: "w_key", char: "열쇠", roman: "yeolsoe", meaning: "Key" },
    { id: "w_sleep", char: "잠", roman: "jam", meaning: "Sleep" },
    { id: "w_tuesday", char: "화요일", roman: "hwayoil", meaning: "Tuesday" },
    { id: "w_wednesday", char: "수요일", roman: "suyoil", meaning: "Wednesday" },
    { id: "w_thursday", char: "목요일", roman: "mogyoil", meaning: "Thursday" },
    { id: "w_friday", char: "금요일", roman: "geumyoil", meaning: "Friday" },
    { id: "w_saturday", char: "토요일", roman: "toyoil", meaning: "Saturday" },
    { id: "w_sunday", char: "일요일", roman: "iryoil", meaning: "Sunday" },
    {
      id: "w_youre_welcome",
      char: "천만에요",
      roman: "cheonmaneyo",
      meaning: "You're welcome",
    },
    {
      id: "w_excuse_me",
      char: "실례합니다",
      roman: "sillyehamnida",
      meaning: "Excuse me",
    },
    {
      id: "w_before_eating",
      char: "잘 먹겠습니다",
      roman: "jal meokgesseumnida",
      meaning: "Before eating (Bon appétit)",
    },
    {
      id: "w_after_eating",
      char: "잘 먹었습니다",
      roman: "jal meogeosseumnida",
      meaning: "After eating (Thank you for the meal)",
    },
    { id: "w_i_love_you", char: "사랑해요", roman: "saranghaeyo", meaning: "I love you" },
    {
      id: "w_goodbye_stay",
      char: "안녕히 계세요",
      roman: "annyeonghi gyeseyo",
      meaning: "Goodbye (to someone staying)",
    },
    { id: "w_grape", char: "포도", roman: "podo", meaning: "Grape" },
    { id: "w_strawberry", char: "딸기", roman: "ttalgi", meaning: "Strawberry" },
    { id: "w_orange", char: "오렌지", roman: "orenji", meaning: "Orange" },
    { id: "w_pizza", char: "피자", roman: "pija", meaning: "Pizza" },
    { id: "w_hamburger", char: "햄버거", roman: "haembeogeo", meaning: "Hamburger" },
    { id: "w_stew", char: "찌개", roman: "jjigae", meaning: "Stew" },
    { id: "w_medicine", char: "약", roman: "yak", meaning: "Medicine" },
    { id: "w_stomach", char: "배", roman: "bae", meaning: "Stomach / Belly" },
    { id: "w_back", char: "등", roman: "deung", meaning: "Back" },
    { id: "w_leg", char: "다리", roman: "dari", meaning: "Leg" },
    { id: "w_spring", char: "봄", roman: "bom", meaning: "Spring" },
    { id: "w_summer", char: "여름", roman: "yeoreum", meaning: "Summer" },
    { id: "w_autumn", char: "가을", roman: "gaeul", meaning: "Autumn" },
    { id: "w_winter", char: "겨울", roman: "gyeoul", meaning: "Winter" },
    { id: "w_hot", char: "더워요", roman: "deowoyo", meaning: "It's hot" },
    { id: "w_cold", char: "추워요", roman: "chuwoyo", meaning: "It's cold" },
    { id: "w_beach", char: "해변", roman: "haebyeon", meaning: "Beach" },
    { id: "w_island", char: "섬", roman: "seom", meaning: "Island" },
    { id: "w_station", char: "역", roman: "yeok", meaning: "Station" },
    { id: "w_train", char: "기차", roman: "gicha", meaning: "Train" },
    { id: "w_bicycle", char: "자전거", roman: "jajeongeo", meaning: "Bicycle" },
    { id: "w_ship", char: "선박", roman: "seonbak", meaning: "Ship" },
    { id: "w_clock", char: "시계", roman: "sigye", meaning: "Clock / Watch" },
    { id: "w_mirror", char: "거울", roman: "geoul", meaning: "Mirror" },
    { id: "w_toothbrush", char: "칫솔", roman: "chitsol", meaning: "Toothbrush" },
    { id: "w_towel", char: "수건", roman: "sugeon", meaning: "Towel" },
    { id: "w_soap", char: "비누", roman: "binu", meaning: "Soap" },
    { id: "w_order", char: "주문", roman: "jumun", meaning: "Order" },
    { id: "w_arm", char: "팔", roman: "pal", meaning: "Arm" },
    { id: "w_shoulder", char: "어깨", roman: "eokkae", meaning: "Shoulder" },
    { id: "w_knee", char: "무릎", roman: "mureup", meaning: "Knee" },
    { id: "w_finger", char: "손가락", roman: "songarak", meaning: "Finger" },
    { id: "w_tooth", char: "이빨", roman: "ippal", meaning: "Tooth" },
    { id: "w_heart", char: "심장", roman: "simjang", meaning: "Heart" },
    { id: "w_neck", char: "목", roman: "mok", meaning: "Neck / Throat" },
    { id: "w_tofu", char: "두부", roman: "dubu", meaning: "Tofu" },
    { id: "w_dumpling", char: "만두", roman: "mandu", meaning: "Dumpling" },
    { id: "w_noodles", char: "국수", roman: "guksu", meaning: "Noodles" },
    { id: "w_cheese", char: "치즈", roman: "chijeu", meaning: "Cheese" },
    { id: "w_cake", char: "케이크", roman: "keikeu", meaning: "Cake" },
    { id: "w_onion", char: "양파", roman: "yangpa", meaning: "Onion" },
    { id: "w_pepper", char: "고추", roman: "gochu", meaning: "Pepper / Chili" },
    { id: "w_black", char: "검은색", roman: "geomeunsaek", meaning: "Black" },
    { id: "w_white", char: "흰색", roman: "huinsaek", meaning: "White" },
    { id: "w_purple", char: "보라색", roman: "borasaek", meaning: "Purple" },
    { id: "w_husband", char: "남편", roman: "nampyeon", meaning: "Husband" },
    { id: "w_wife", char: "아내", roman: "anae", meaning: "Wife" },
    { id: "w_parents", char: "부모", roman: "bumo", meaning: "Parents" },
    { id: "w_week", char: "주", roman: "ju", meaning: "Week" },
    { id: "w_month", char: "월", roman: "wol", meaning: "Month" },
    { id: "w_year", char: "년", roman: "nyeon", meaning: "Year" },
    { id: "w_cafe", char: "카페", roman: "kape", meaning: "Cafe" },
    {
      id: "w_cinema",
      char: "영화관",
      roman: "yeonghwagwan",
      meaning: "Movie theater",
    },
    { id: "w_office", char: "사무실", roman: "samusil", meaning: "Office" },
    { id: "w_ticket", char: "표", roman: "pyo", meaning: "Ticket" },
    { id: "w_map", char: "지도", roman: "jido", meaning: "Map" },
    { id: "w_passport", char: "여권", roman: "yeogwon", meaning: "Passport" },
    { id: "w_rabbit", char: "토끼", roman: "tokki", meaning: "Rabbit" },
    { id: "w_bear", char: "곰", roman: "gom", meaning: "Bear" },
    { id: "w_duck", char: "오리", roman: "ori", meaning: "Duck" },
    { id: "w_eat", char: "먹어요", roman: "meogeoyo", meaning: "Eat" },
    { id: "w_drink", char: "마셔요", roman: "masyeoyo", meaning: "Drink" },
    { id: "w_read", char: "읽어요", roman: "ilgeoyo", meaning: "Read" },
    { id: "w_watch", char: "봐요", roman: "bwayo", meaning: "Watch / Look" },
    { id: "w_hungry", char: "배고파요", roman: "baegopayo", meaning: "I'm hungry" },
    { id: "w_tired", char: "피곤해요", roman: "pigonhaeyo", meaning: "I'm tired" },
    { id: "w_good_night", char: "잘 자요", roman: "jal jayo", meaning: "Good night" },
    { id: "w_airplane", char: "비행기", roman: "bihaenggi", meaning: "Airplane" },
    { id: "w_waist", char: "허리", roman: "heori", meaning: "Waist" },
    { id: "w_chest", char: "가슴", roman: "gaseum", meaning: "Chest" },
    { id: "w_body", char: "몸", roman: "mom", meaning: "Body" },
    { id: "w_height", char: "키", roman: "ki", meaning: "Height" },
    { id: "w_carrot", char: "당근", roman: "danggeun", meaning: "Carrot" },
    { id: "w_potato", char: "감자", roman: "gamja", meaning: "Potato" },
    { id: "w_mushroom", char: "버섯", roman: "beoseot", meaning: "Mushroom" },
    { id: "w_butter", char: "버터", roman: "beoteo", meaning: "Butter" },
    { id: "w_honey", char: "꿀", roman: "kkul", meaning: "Honey" },
    { id: "w_soybean_paste", char: "된장", roman: "doenjang", meaning: "Soybean paste" },
    { id: "w_bowl", char: "그릇", roman: "geurut", meaning: "Bowl" },
    { id: "w_spoon", char: "숟가락", roman: "sutgarak", meaning: "Spoon" },
    { id: "w_chopsticks", char: "젓가락", roman: "jeotgarak", meaning: "Chopsticks" },
    { id: "w_elephant", char: "코끼리", roman: "kokkiri", meaning: "Elephant" },
    { id: "w_lion", char: "사자", roman: "saja", meaning: "Lion" },
    { id: "w_monkey", char: "원숭이", roman: "wonsungi", meaning: "Monkey" },
    { id: "w_turtle", char: "거북이", roman: "geobugi", meaning: "Turtle" },
    { id: "w_butterfly", char: "나비", roman: "nabi", meaning: "Butterfly" },
    { id: "w_chicken_animal", char: "닭", roman: "dak", meaning: "Chicken (animal)" },
    { id: "w_ball", char: "공", roman: "gong", meaning: "Ball" },
    { id: "w_gift", char: "선물", roman: "seonmul", meaning: "Gift" },
    { id: "w_camera", char: "카메라", roman: "kamera", meaning: "Camera" },
    { id: "w_refrigerator", char: "냉장고", roman: "naengjanggo", meaning: "Refrigerator" },
    { id: "w_washing_machine", char: "세탁기", roman: "setakgi", meaning: "Washing machine" },
    { id: "w_here", char: "여기", roman: "yeogi", meaning: "Here" },
    { id: "w_there", char: "거기", roman: "geogi", meaning: "There" },
    { id: "w_this", char: "이거", roman: "igeo", meaning: "This" },
    { id: "w_how_much", char: "얼마", roman: "eolma", meaning: "How much" },
    { id: "w_expensive", char: "비싸요", roman: "bissayo", meaning: "It's expensive" },
    { id: "w_cheap", char: "싸요", roman: "ssayo", meaning: "It's cheap" },
    { id: "w_difficult", char: "어려워요", roman: "eoryeowoyo", meaning: "It's difficult" },
    { id: "w_easy", char: "쉬워요", roman: "swiwoyo", meaning: "It's easy" },
    { id: "w_listen", char: "들어요", roman: "deureoyo", meaning: "Listen" },
    { id: "w_buy", char: "사요", roman: "sayo", meaning: "Buy" },
    { id: "w_wait", char: "기다려요", roman: "gidaryeoyo", meaning: "Wait" },
    { id: "w_write", char: "써요", roman: "sseoyo", meaning: "Write" },
    { id: "w_shopping", char: "쇼핑", roman: "syoping", meaning: "Shopping" },
    { id: "w_laundry", char: "빨래", roman: "ppallae", meaning: "Laundry" },
    { id: "w_cleaning", char: "청소", roman: "cheongso", meaning: "Cleaning" },
    { id: "w_fun", char: "재미있어요", roman: "jaemiisseoyo", meaning: "It's fun / interesting" },
    { id: "w_knife", char: "칼", roman: "kal", meaning: "Knife" },
    { id: "w_fork", char: "포크", roman: "pokeu", meaning: "Fork" },
    { id: "w_plate", char: "접시", roman: "jeopsi", meaning: "Plate" },
    { id: "w_cup", char: "컵", roman: "keop", meaning: "Cup" },
    { id: "w_pot", char: "냄비", roman: "naembi", meaning: "Pot" },
    {
      id: "w_microwave",
      char: "전자레인지",
      roman: "jeonjareinji",
      meaning: "Microwave",
    },
    { id: "w_aircon", char: "에어컨", roman: "eeokeon", meaning: "Air conditioner" },
    { id: "w_tv", char: "텔레비전", roman: "tellebijeon", meaning: "TV" },
    { id: "w_desk", char: "책상", roman: "chaeksang", meaning: "Desk" },
    { id: "w_chair", char: "의자", roman: "uija", meaning: "Chair" },
    { id: "w_table", char: "탁자", roman: "takja", meaning: "Table" },
    { id: "w_sofa", char: "소파", roman: "sopa", meaning: "Sofa" },
    { id: "w_blanket", char: "이불", roman: "ibul", meaning: "Blanket" },
    { id: "w_pillow", char: "베개", roman: "begae", meaning: "Pillow" },
    { id: "w_scissors", char: "가위", roman: "gawi", meaning: "Scissors" },
    { id: "w_left", char: "왼쪽", roman: "oenjjok", meaning: "Left" },
    { id: "w_right", char: "오른쪽", roman: "oreunjjok", meaning: "Right" },
    { id: "w_front", char: "앞", roman: "ap", meaning: "Front" },
    { id: "w_back_side", char: "뒤", roman: "dwi", meaning: "Back / Behind" },
    { id: "w_inside", char: "안", roman: "an", meaning: "Inside" },
    { id: "w_outside", char: "밖", roman: "bak", meaning: "Outside" },
    { id: "w_over_there", char: "저기", roman: "jeogi", meaning: "Over there" },
    {
      id: "w_happy",
      char: "행복해요",
      roman: "haengbokhaeyo",
      meaning: "I'm happy",
    },
    { id: "w_sad", char: "슬퍼요", roman: "seulpeoyo", meaning: "I'm sad" },
    { id: "w_dont_know", char: "몰라요", roman: "mollayo", meaning: "I don't know" },
    { id: "w_i_know", char: "알아요", roman: "arayo", meaning: "I know" },
    { id: "w_speak", char: "말해요", roman: "malhaeyo", meaning: "Speak / Talk" },
    { id: "w_walk", char: "걸어요", roman: "georeoyo", meaning: "Walk" },
    { id: "w_run", char: "달려요", roman: "dallyeoyo", meaning: "Run" },
    { id: "w_meet", char: "만나요", roman: "mannayo", meaning: "Meet" },
    { id: "w_shrimp", char: "새우", roman: "saeu", meaning: "Shrimp" },
    { id: "w_pork", char: "돼지고기", roman: "dwaejigogi", meaning: "Pork" },
    { id: "w_beef", char: "소고기", roman: "sogogi", meaning: "Beef" },
    { id: "w_cabbage", char: "배추", roman: "baechu", meaning: "Cabbage" },
    { id: "w_garlic", char: "마늘", roman: "maneul", meaning: "Garlic" },
    { id: "w_spinach", char: "시금치", roman: "sigeumchi", meaning: "Spinach" },
    { id: "w_snake", char: "뱀", roman: "baem", meaning: "Snake" },
    { id: "w_frog", char: "개구리", roman: "gaeguri", meaning: "Frog" },
    { id: "w_dolphin", char: "돌고래", roman: "dolgorae", meaning: "Dolphin" },
    { id: "w_museum", char: "박물관", roman: "bangmulgwan", meaning: "Museum" },
    { id: "w_pencil", char: "연필", roman: "yeonpil", meaning: "Pencil" },
    { id: "w_notebook", char: "공책", roman: "gongchaek", meaning: "Notebook" },
    { id: "w_wallet", char: "지갑", roman: "jigap", meaning: "Wallet" },
    { id: "w_tissue", char: "휴지", roman: "hyuji", meaning: "Tissue" },
    { id: "w_shampoo", char: "샴푸", roman: "syampu", meaning: "Shampoo" },
    { id: "w_cloud", char: "구름", roman: "gureum", meaning: "Cloud" },
    { id: "w_fog", char: "안개", roman: "angae", meaning: "Fog" },
    { id: "w_soy_sauce", char: "간장", roman: "ganjang", meaning: "Soy sauce" },
    { id: "w_vinegar", char: "식초", roman: "sikcho", meaning: "Vinegar" },
    { id: "w_bean", char: "콩", roman: "kong", meaning: "Bean" },
    { id: "w_corn", char: "옥수수", roman: "oksusu", meaning: "Corn" },
    {
      id: "w_hair_salon",
      char: "미용실",
      roman: "miyongsil",
      meaning: "Hair salon",
    },
    {
      id: "w_supermarket",
      char: "슈퍼마켓",
      roman: "syupeomaket",
      meaning: "Supermarket",
    },
    { id: "w_zoo", char: "동물원", roman: "dongmurwon", meaning: "Zoo" },
    {
      id: "w_swimming_pool",
      char: "수영장",
      roman: "suyeonjang",
      meaning: "Swimming pool",
    },
    { id: "w_gym", char: "체육관", roman: "cheyukgwan", meaning: "Gym" },
    { id: "w_pretty", char: "예뻐요", roman: "yeppeoyo", meaning: "It's pretty" },
    { id: "w_big", char: "커요", roman: "keoyo", meaning: "It's big" },
    { id: "w_small", char: "작아요", roman: "jagayo", meaning: "It's small" },
    { id: "w_wake_up", char: "일어나요", roman: "ireonayo", meaning: "Wake up" },
    { id: "w_sleep_verb", char: "자요", roman: "jayo", meaning: "Sleep" },
    { id: "w_wash", char: "씻어요", roman: "ssiseoyo", meaning: "Wash" },
    { id: "w_cook", char: "요리해요", roman: "yorihaeyo", meaning: "Cook" },
    { id: "w_work_verb", char: "일해요", roman: "ilhaeyo", meaning: "Work" },
    { id: "w_play", char: "놀아요", roman: "norayo", meaning: "Play" },
    { id: "w_sing", char: "노래해요", roman: "noraehaeyo", meaning: "Sing" },
    {
      id: "w_call",
      char: "전화해요",
      roman: "jeonhwahaeyo",
      meaning: "Call (phone)",
    },
    { id: "w_learn", char: "배워요", roman: "baewoyo", meaning: "Learn" },
    { id: "w_aunt", char: "이모", roman: "imo", meaning: "Aunt (mother's side)" },
    { id: "w_uncle", char: "삼촌", roman: "samchon", meaning: "Uncle" },
    { id: "w_cousin", char: "사촌", roman: "sachon", meaning: "Cousin" },
    { id: "w_neighborhood", char: "동네", roman: "dongne", meaning: "Neighborhood" },
    { id: "w_basement", char: "지하", roman: "jiha", meaning: "Basement / Underground" },
    { id: "w_rooftop", char: "옥상", roman: "oksang", meaning: "Rooftop" },
    {
      id: "w_elevator",
      char: "엘리베이터",
      roman: "ellibeiteo",
      meaning: "Elevator",
    },
    { id: "w_stairs", char: "계단", roman: "gyedan", meaning: "Stairs" },
    { id: "w_makeup", char: "화장", roman: "hwajang", meaning: "Makeup" },
    { id: "w_perfume", char: "향수", roman: "hyangsu", meaning: "Perfume" },
    { id: "w_side_dish", char: "반찬", roman: "banchan", meaning: "Side dish" },
    {
      id: "w_good_morning",
      char: "좋은 아침이에요",
      roman: "joeun achimieyo",
      meaning: "Good morning",
    },
    { id: "w_tomato", char: "토마토", roman: "tomato", meaning: "Tomato" },
    { id: "w_cucumber", char: "오이", roman: "oi", meaning: "Cucumber" },
    { id: "w_sweet_potato", char: "고구마", roman: "goguma", meaning: "Sweet potato" },
    { id: "w_snack", char: "과자", roman: "gwaja", meaning: "Snack" },
    { id: "w_kimbap", char: "김밥", roman: "gimbap", meaning: "Kimbap" },
    { id: "w_tteokbokki", char: "떡볶이", roman: "tteokbokki", meaning: "Tteokbokki" },
    { id: "w_parking_lot", char: "주차장", roman: "juchajang", meaning: "Parking lot" },
    { id: "w_art_museum", char: "미술관", roman: "misulgwan", meaning: "Art museum" },
    { id: "w_farm", char: "농장", roman: "nongjang", meaning: "Farm" },
    { id: "w_church", char: "교회", roman: "gyohoe", meaning: "Church" },
    { id: "w_open", char: "열어요", roman: "yeoreoyo", meaning: "Open" },
    { id: "w_close", char: "닫아요", roman: "dadayo", meaning: "Close" },
    { id: "w_find", char: "찾아요", roman: "chajayo", meaning: "Find / Look for" },
    { id: "w_laugh", char: "웃어요", roman: "useoyo", meaning: "Laugh / Smile" },
    { id: "w_cry", char: "울어요", roman: "ureoyo", meaning: "Cry" },
    { id: "w_sit", char: "앉아요", roman: "anjayo", meaning: "Sit" },
    { id: "w_stand", char: "서요", roman: "seoyo", meaning: "Stand" },
    { id: "w_ride", char: "타요", roman: "tayo", meaning: "Ride / Get on" },
    { id: "w_start", char: "시작해요", roman: "sijakhaeyo", meaning: "Start" },
    { id: "w_end", char: "끝나요", roman: "kkeunnayo", meaning: "End / Finish" },
    { id: "w_pants", char: "바지", roman: "baji", meaning: "Pants" },
    { id: "w_shirt", char: "셔츠", roman: "syeocheu", meaning: "Shirt" },
    { id: "w_socks", char: "양말", roman: "yangmal", meaning: "Socks" },
    { id: "w_gloves", char: "장갑", roman: "janggap", meaning: "Gloves" },
    { id: "w_newspaper", char: "신문", roman: "sinmun", meaning: "Newspaper" },
    { id: "w_magazine", char: "잡지", roman: "japji", meaning: "Magazine" },
    { id: "w_earphones", char: "이어폰", roman: "ieopeon", meaning: "Earphones" },
    { id: "w_charger", char: "충전기", roman: "chungjeongi", meaning: "Charger" },
    { id: "w_battery", char: "배터리", roman: "baeteori", meaning: "Battery" },
    { id: "w_fan", char: "선풍기", roman: "seonpunggi", meaning: "Electric fan" },
    { id: "w_lamp", char: "전등", roman: "jeondeung", meaning: "Light / Lamp" },
    { id: "w_toothpaste", char: "치약", roman: "chiyak", meaning: "Toothpaste" },
    { id: "w_hello_casual", char: "안녕", roman: "annyeong", meaning: "Hello (casual)" },
    { id: "w_good_job", char: "수고해요", roman: "sugohaeyo", meaning: "Good job / Thanks for your work" },
    { id: "w_busy", char: "바빠요", roman: "bappayo", meaning: "I'm busy" },
    { id: "w_scared", char: "무서워요", roman: "museowoyo", meaning: "I'm scared" },
    { id: "w_lightning", char: "번개", roman: "beongae", meaning: "Lightning" },
    { id: "w_doctor", char: "의사", roman: "uisa", meaning: "Doctor" },
    { id: "w_nurse", char: "간호사", roman: "ganhosa", meaning: "Nurse" },
    { id: "w_day_after_tomorrow", char: "모레", roman: "more", meaning: "Day after tomorrow" },
    { id: "w_thunder", char: "천둥", roman: "cheondung", meaning: "Thunder" },
    { id: "w_typhoon", char: "태풍", roman: "taepung", meaning: "Typhoon" },
    { id: "w_sand", char: "모래", roman: "morae", meaning: "Sand" },
    { id: "w_stone", char: "돌", roman: "dol", meaning: "Stone" },
    { id: "w_grass", char: "풀", roman: "pul", meaning: "Grass" },
    { id: "w_leaf", char: "잎", roman: "ip", meaning: "Leaf" },
    { id: "w_forest", char: "숲", roman: "sup", meaning: "Forest" },
    { id: "w_lake", char: "호수", roman: "hosu", meaning: "Lake" },
    { id: "w_sheep", char: "양", roman: "yang", meaning: "Sheep" },
    { id: "w_fox", char: "여우", roman: "yeou", meaning: "Fox" },
    { id: "w_squirrel", char: "다람쥐", roman: "daramjwi", meaning: "Squirrel" },
    { id: "w_bee", char: "벌", roman: "beol", meaning: "Bee" },
    { id: "w_mouse", char: "쥐", roman: "jwi", meaning: "Mouse / Rat" },
    { id: "w_squid", char: "오징어", roman: "ojingeo", meaning: "Squid" },
    { id: "w_crab", char: "게", roman: "ge", meaning: "Crab" },
    { id: "w_spaghetti", char: "스파게티", roman: "seupageti", meaning: "Spaghetti" },
    { id: "w_sandwich", char: "샌드위치", roman: "saendeuwichi", meaning: "Sandwich" },
    { id: "w_hotdog", char: "핫도그", roman: "hatdogeu", meaning: "Hot dog" },
    { id: "w_mango", char: "망고", roman: "manggo", meaning: "Mango" },
    { id: "w_peach", char: "복숭아", roman: "boksunga", meaning: "Peach" },
    { id: "w_lemon", char: "레몬", roman: "remon", meaning: "Lemon" },
    { id: "w_green_onion", char: "파", roman: "pa", meaning: "Green onion" },
    { id: "w_pork_belly", char: "삼겹살", roman: "samgyeopsal", meaning: "Pork belly" },
    { id: "w_soy_milk", char: "두유", roman: "duyu", meaning: "Soy milk" },
    { id: "w_yogurt", char: "요구르트", roman: "yogeureuteu", meaning: "Yogurt" },
    { id: "w_sausage", char: "소시지", roman: "sosiji", meaning: "Sausage" },
    { id: "w_angry", char: "화나요", roman: "hwanayo", meaning: "I'm angry" },
    { id: "w_worried", char: "걱정돼요", roman: "geokjeongdwaeyo", meaning: "I'm worried" },
    { id: "w_bored", char: "심심해요", roman: "simsimhaeyo", meaning: "I'm bored" },
    { id: "w_sleepy", char: "졸려요", roman: "jollyeoyo", meaning: "I'm sleepy" },
    { id: "w_warm", char: "따뜻해요", roman: "ttatteuthaeyo", meaning: "It's warm" },
    { id: "w_cool", char: "시원해요", roman: "siwonhaeyo", meaning: "It's cool / refreshing" },
    { id: "w_not_tasty", char: "맛없어요", roman: "maseopseoyo", meaning: "It's not tasty" },
    { id: "w_send", char: "보내요", roman: "bonaeyo", meaning: "Send" },
    { id: "w_receive", char: "받아요", roman: "badayo", meaning: "Receive" },
    { id: "w_teach", char: "가르쳐요", roman: "galeuchyeoyo", meaning: "Teach" },
    { id: "w_prepare", char: "준비해요", roman: "junbihaeyo", meaning: "Prepare" },
    { id: "w_organize", char: "정리해요", roman: "jeongnihaeyo", meaning: "Organize / Tidy up" },
    { id: "w_rest", char: "쉬어요", roman: "swieoyo", meaning: "Rest" },
    { id: "w_dance", char: "춤춰요", roman: "chumchwoyo", meaning: "Dance" },
    { id: "w_draw", char: "그려요", roman: "geuryeoyo", meaning: "Draw" },
    { id: "w_clean_verb", char: "청소해요", roman: "cheongsohaeyo", meaning: "Clean" },
    { id: "w_borrow", char: "빌려요", roman: "billyeoyo", meaning: "Borrow" },
    { id: "w_sell", char: "팔아요", roman: "parayo", meaning: "Sell" },
    { id: "w_welcome", char: "환영해요", roman: "hwanyeonghaeyo", meaning: "Welcome" },
    {
      id: "w_nice_to_work_with",
      char: "잘 부탁해요",
      roman: "jal butakaeyo",
      meaning: "Please take care of it / Nice to work with you",
    },
    {
      id: "w_come_in",
      char: "어서 오세요",
      roman: "eoseo oseyo",
      meaning: "Welcome (to a place)",
    },
    { id: "w_be_careful", char: "조심하세요", roman: "josimhaseyo", meaning: "Be careful" },
    {
      id: "w_im_back",
      char: "다녀왔습니다",
      roman: "danyeowasseumnida",
      meaning: "I'm back (home)",
    },
    { id: "w_ago", char: "아까", roman: "akka", meaning: "A little while ago" },
    { id: "w_later", char: "나중에", roman: "najunge", meaning: "Later" },
    { id: "w_always", char: "항상", roman: "hangsang", meaning: "Always" },
    { id: "w_sometimes", char: "가끔", roman: "gakkeum", meaning: "Sometimes" },
    { id: "w_often", char: "자주", roman: "jaju", meaning: "Often" },
    { id: "w_just_now", char: "방금", roman: "banggeum", meaning: "Just now" },
    { id: "w_alone", char: "혼자", roman: "honja", meaning: "Alone" },
    { id: "w_together", char: "같이", roman: "gachi", meaning: "Together" },
    { id: "w_university", char: "대학교", roman: "daehakgyo", meaning: "University" },
    { id: "w_kindergarten", char: "유치원", roman: "yuchiwon", meaning: "Kindergarten" },
    { id: "w_concert_hall", char: "공연장", roman: "gongyeonjang", meaning: "Concert hall" },
    { id: "w_kitchen", char: "주방", roman: "jubang", meaning: "Kitchen" },
    { id: "w_living_room", char: "거실", roman: "geosil", meaning: "Living room" },
    { id: "w_room", char: "방", roman: "bang", meaning: "Room" },
    { id: "w_wall", char: "벽", roman: "byeok", meaning: "Wall" },
    { id: "w_floor", char: "바닥", roman: "badak", meaning: "Floor" },
    { id: "w_closet", char: "옷장", roman: "otjang", meaning: "Closet" },
    { id: "w_comb", char: "빗", roman: "bit", meaning: "Comb" },
    { id: "w_trash_can", char: "쓰레기통", roman: "sseuregitong", meaning: "Trash can" },
    { id: "w_broom", char: "빗자루", roman: "bitjaru", meaning: "Broom" },
    { id: "w_motorcycle", char: "오토바이", roman: "otobai", meaning: "Motorcycle" },
    { id: "w_truck", char: "트럭", roman: "teureok", meaning: "Truck" },
    { id: "w_traffic_light", char: "신호등", roman: "sinhodeung", meaning: "Traffic light" },
    { id: "w_police_officer", char: "경찰", roman: "gyeongchal", meaning: "Police officer" },
    { id: "w_firefighter", char: "소방관", roman: "sobanggwan", meaning: "Firefighter" },
    { id: "w_chef", char: "요리사", roman: "yorisa", meaning: "Chef" },
    { id: "w_driver", char: "운전사", roman: "unjeonsa", meaning: "Driver" },
    { id: "w_flight_attendant", char: "승무원", roman: "seungmuwon", meaning: "Flight attendant" },
    { id: "w_correct", char: "맞아요", roman: "majayo", meaning: "That's right / Correct" },
    { id: "w_how_many", char: "몇", roman: "myeot", meaning: "How many / Several" },
    { id: "w_address", char: "주소", roman: "juso", meaning: "Address" },
    { id: "w_son", char: "아들", roman: "adeul", meaning: "Son" },
    { id: "w_daughter", char: "딸", roman: "ttal", meaning: "Daughter" },
    { id: "w_grandson", char: "손자", roman: "sonja", meaning: "Grandson" },
    { id: "w_granddaughter", char: "손녀", roman: "sonyeo", meaning: "Granddaughter" },
    { id: "w_nephew_niece", char: "조카", roman: "joka", meaning: "Nephew / Niece" },
    { id: "w_brothers", char: "형제", roman: "hyeongje", meaning: "Brothers / Siblings" },
    { id: "w_sisters", char: "자매", roman: "jamae", meaning: "Sisters" },
    { id: "w_tongue", char: "혀", roman: "hyeo", meaning: "Tongue" },
    { id: "w_skin", char: "피부", roman: "pibu", meaning: "Skin" },
    { id: "w_bone", char: "뼈", roman: "ppyeo", meaning: "Bone" },
    { id: "w_blood", char: "피", roman: "pi", meaning: "Blood" },
    { id: "w_bus_stop", char: "정류장", roman: "jeongnyujang", meaning: "Bus stop" },
    { id: "w_city_hall", char: "시청", roman: "sicheong", meaning: "City hall" },
    { id: "w_temple", char: "사원", roman: "sawon", meaning: "Temple" },
    { id: "w_port", char: "항구", roman: "hanggu", meaning: "Port" },
    { id: "w_seaweed", char: "김", roman: "gim", meaning: "Seaweed / Laver" },
    { id: "w_dried_anchovy", char: "멸치", roman: "myeolchi", meaning: "Dried anchovy" },
    { id: "w_tuna", char: "참치", roman: "chamchi", meaning: "Tuna" },
    { id: "w_salmon", char: "연어", roman: "yeoneo", meaning: "Salmon" },
    { id: "w_broccoli", char: "브로콜리", roman: "beurokollori", meaning: "Broccoli" },
    { id: "w_lettuce", char: "상추", roman: "sangchu", meaning: "Lettuce" },
    { id: "w_radish", char: "무", roman: "mu", meaning: "Radish" },
    { id: "w_tangerine", char: "귤", roman: "gyul", meaning: "Tangerine" },
    { id: "w_kiwi", char: "키위", roman: "kiwi", meaning: "Kiwi" },
    { id: "w_chocolate", char: "초콜릿", roman: "chokollit", meaning: "Chocolate" },
    { id: "w_candy", char: "사탕", roman: "satang", meaning: "Candy" },
    { id: "w_bulgogi", char: "불고기", roman: "bulgogi", meaning: "Bulgogi" },
    { id: "w_bibimbap", char: "비빔밥", roman: "bibimbap", meaning: "Bibimbap" },
    { id: "w_tiger", char: "호랑이", roman: "horangi", meaning: "Tiger" },
    { id: "w_wolf", char: "늑대", roman: "neukdae", meaning: "Wolf" },
    { id: "w_penguin", char: "펭귄", roman: "penggwin", meaning: "Penguin" },
    { id: "w_eagle", char: "독수리", roman: "doksuri", meaning: "Eagle" },
    { id: "w_parrot", char: "앵무새", roman: "aengmusae", meaning: "Parrot" },
    { id: "w_spider", char: "거미", roman: "geomi", meaning: "Spider" },
    { id: "w_ant", char: "개미", roman: "gaemi", meaning: "Ant" },
    { id: "w_snail", char: "달팽이", roman: "dalpaengi", meaning: "Snail" },
    { id: "w_make", char: "만들어요", roman: "mandeureoyo", meaning: "Make" },
    { id: "w_give", char: "줘요", roman: "jwoyo", meaning: "Give" },
    { id: "w_take_away", char: "가져가요", roman: "gajyeogayo", meaning: "Take away" },
    { id: "w_bring", char: "가져와요", roman: "gajyeowayo", meaning: "Bring" },
    { id: "w_enter", char: "들어가요", roman: "deureogayo", meaning: "Enter / Go in" },
    { id: "w_exit", char: "나가요", roman: "nagayo", meaning: "Exit / Go out" },
    { id: "w_go_up", char: "올라가요", roman: "ollagayo", meaning: "Go up" },
    { id: "w_go_down", char: "내려가요", roman: "naeryeogayo", meaning: "Go down" },
    { id: "w_go_back", char: "돌아가요", roman: "doragayo", meaning: "Go back" },
    { id: "w_come_back", char: "돌아와요", roman: "dorawayo", meaning: "Come back" },
    { id: "w_remember", char: "기억해요", roman: "gieokhaeyo", meaning: "Remember" },
    { id: "w_forget", char: "잊어요", roman: "ijeoyo", meaning: "Forget" },
    { id: "w_think", char: "생각해요", roman: "saenggakhaeyo", meaning: "Think" },
    { id: "w_believe", char: "믿어요", roman: "mideoyo", meaning: "Believe" },
    { id: "w_use", char: "사용해요", roman: "sayonghaeyo", meaning: "Use" },
    { id: "w_need", char: "필요해요", roman: "piryohaeyo", meaning: "Need" },
    { id: "w_dislike", char: "싫어해요", roman: "sireohaeyo", meaning: "Dislike" },
    { id: "w_many", char: "많아요", roman: "manayo", meaning: "There are many / A lot" },
    { id: "w_few", char: "적어요", roman: "jeogeoyo", meaning: "There are few" },
    { id: "w_fast", char: "빨라요", roman: "ppallayo", meaning: "It's fast" },
    { id: "w_slow", char: "느려요", roman: "neuryeoyo", meaning: "It's slow" },
    { id: "w_tall", char: "높아요", roman: "nopayo", meaning: "It's tall / High" },
    { id: "w_low", char: "낮아요", roman: "najayo", meaning: "It's low" },
    { id: "w_long", char: "길어요", roman: "gireoyo", meaning: "It's long" },
    { id: "w_short", char: "짧아요", roman: "jjalbajyo", meaning: "It's short" },
    { id: "w_heavy", char: "무거워요", roman: "mugeowoyo", meaning: "It's heavy" },
    { id: "w_light_weight", char: "가벼워요", roman: "gabyeowoyo", meaning: "It's light (weight)" },
    { id: "w_clean_adj", char: "깨끗해요", roman: "kkaekkeuthaeyo", meaning: "It's clean" },
    { id: "w_dirty", char: "더러워요", roman: "deoreowoyo", meaning: "It's dirty" },
    { id: "w_quiet", char: "조용해요", roman: "joyonghaeyo", meaning: "It's quiet" },
    { id: "w_noisy", char: "시끄러워요", roman: "sikkeureowoyo", meaning: "It's noisy" },
    { id: "w_bright", char: "밝아요", roman: "balgayo", meaning: "It's bright" },
    { id: "w_dark", char: "어두워요", roman: "eoduwoyo", meaning: "It's dark" },
    { id: "w_smartphone", char: "스마트폰", roman: "seumateupon", meaning: "Smartphone" },
    { id: "w_tablet", char: "태블릿", roman: "taeblet", meaning: "Tablet" },
    { id: "w_laptop", char: "노트북", roman: "noteubuk", meaning: "Laptop" },
    { id: "w_wifi", char: "와이파이", roman: "waipai", meaning: "Wi-Fi" },
    { id: "w_email", char: "이메일", roman: "imeil", meaning: "Email" },
    { id: "w_message", char: "메시지", roman: "mesiji", meaning: "Message" },
    { id: "w_textbook", char: "교과서", roman: "gyogwaseo", meaning: "Textbook" },
    { id: "w_pencil_case", char: "필통", roman: "piltong", meaning: "Pencil case" },
    { id: "w_ruler", char: "자", roman: "ja", meaning: "Ruler" },
    { id: "w_calculator", char: "계산기", roman: "gyesanggi", meaning: "Calculator" },
    { id: "w_exam", char: "시험", roman: "siheom", meaning: "Exam" },
    { id: "w_score", char: "점수", roman: "jeomsu", meaning: "Score" },
    { id: "w_class", char: "수업", roman: "sueop", meaning: "Class / Lesson" },
    { id: "w_school_lunch", char: "급식", roman: "geupsik", meaning: "School lunch" },
    { id: "w_afternoon", char: "오후", roman: "ohu", meaning: "Afternoon" },
    { id: "w_morning_am", char: "오전", roman: "ojeon", meaning: "Morning (AM)" },
    { id: "w_noon", char: "낮", roman: "nat", meaning: "Daytime / Noon" },
    { id: "w_dawn", char: "새벽", roman: "saebyeok", meaning: "Dawn" },
    { id: "w_one_week", char: "일주일", roman: "iljuil", meaning: "One week" },
    { id: "w_one_day", char: "하루", roman: "haru", meaning: "One day" },
    { id: "w_every_day", char: "매일", roman: "maeil", meaning: "Every day" },
    { id: "w_eleven", char: "열하나", roman: "yeolhana", meaning: "Eleven" },
    { id: "w_twenty", char: "스무", roman: "seumu", meaning: "Twenty" },
    { id: "w_hundred", char: "백", roman: "baek", meaning: "Hundred" },
    { id: "w_skirt", char: "치마", roman: "chima", meaning: "Skirt" },
    { id: "w_dress", char: "원피스", roman: "wonpiseu", meaning: "Dress" },
    { id: "w_coat", char: "코트", roman: "koteu", meaning: "Coat" },
    { id: "w_sneakers", char: "운동화", roman: "undonghwa", meaning: "Sneakers" },
    { id: "w_soccer", char: "축구", roman: "chukgu", meaning: "Soccer" },
    { id: "w_baseball", char: "야구", roman: "yagu", meaning: "Baseball" },
    { id: "w_swimming", char: "수영", roman: "suyeong", meaning: "Swimming" },
    { id: "w_singer", char: "가수", roman: "gasu", meaning: "Singer" },
    { id: "w_actor", char: "배우", roman: "baeu", meaning: "Actor" },
    { id: "w_writer", char: "작가", roman: "jakga", meaning: "Writer" },
    { id: "w_journalist", char: "기자", roman: "gija", meaning: "Journalist" },
    { id: "w_farmer", char: "농부", roman: "nongbu", meaning: "Farmer" },
    { id: "w_fisherman", char: "어부", roman: "eobu", meaning: "Fisherman" },
    { id: "w_boss", char: "사장", roman: "sajang", meaning: "Boss / President" },
    { id: "w_employee", char: "직원", roman: "jigwon", meaning: "Employee" },
    { id: "w_civil_servant", char: "공무원", roman: "gongmuwon", meaning: "Civil servant" },
    { id: "w_lawyer", char: "변호사", roman: "byeonhosa", meaning: "Lawyer" },
    { id: "w_avocado", char: "아보카도", roman: "abokado", meaning: "Avocado" },
    { id: "w_blueberry", char: "블루베리", roman: "beulluberi", meaning: "Blueberry" },
    { id: "w_cherry", char: "체리", roman: "cheri", meaning: "Cherry" },
    { id: "w_persimmon", char: "감", roman: "gam", meaning: "Persimmon" },
    { id: "w_plum", char: "자두", roman: "jadu", meaning: "Plum" },
    { id: "w_cola", char: "콜라", roman: "kolla", meaning: "Cola" },
    { id: "w_galbi", char: "갈비", roman: "galbi", meaning: "Galbi (ribs)" },
    { id: "w_naengmyeon", char: "냉면", roman: "naengmyeon", meaning: "Cold noodles" },
    { id: "w_kalguksu", char: "칼국수", roman: "kalguksu", meaning: "Knife-cut noodles" },
    { id: "w_clam", char: "조개", roman: "jogae", meaning: "Clam" },
    { id: "w_octopus", char: "문어", roman: "muneo", meaning: "Octopus" },
    { id: "w_jokbal", char: "족발", roman: "jokbal", meaning: "Pig's trotters" },
    { id: "w_rice_grain", char: "쌀", roman: "ssal", meaning: "Rice (grain)" },
    { id: "w_flour", char: "밀가루", roman: "milgaru", meaning: "Flour" },
    { id: "w_pepper_spice", char: "후추", roman: "huchu", meaning: "Black pepper" },
    { id: "w_kkakdugi", char: "깍두기", roman: "kkakdugi", meaning: "Cubed radish kimchi" },
    { id: "w_eyebrow", char: "눈썹", roman: "nunsseop", meaning: "Eyebrow" },
    { id: "w_fingernail", char: "손톱", roman: "sontop", meaning: "Fingernail" },
    { id: "w_underwear", char: "속옷", roman: "sot", meaning: "Underwear" },
    { id: "w_terminal", char: "터미널", roman: "teomineol", meaning: "Terminal" },
    { id: "w_intersection", char: "사거리", roman: "sageori", meaning: "Intersection" },
    { id: "w_alley", char: "골목", roman: "golmok", meaning: "Alley" },
    { id: "w_apartment", char: "아파트", roman: "apateu", meaning: "Apartment" },
    { id: "w_palace", char: "궁", roman: "gung", meaning: "Palace" },
    { id: "w_basketball", char: "농구", roman: "nonggu", meaning: "Basketball" },
    { id: "w_tennis", char: "테니스", roman: "teniseu", meaning: "Tennis" },
    { id: "w_badminton", char: "배드민턴", roman: "baedeuminteon", meaning: "Badminton" },
    { id: "w_golf", char: "골프", roman: "golpeu", meaning: "Golf" },
    { id: "w_hiking", char: "등산", roman: "deungsan", meaning: "Hiking" },
    { id: "w_fishing", char: "낚시", roman: "naksi", meaning: "Fishing" },
    { id: "w_piano", char: "피아노", roman: "piano", meaning: "Piano" },
    { id: "w_guitar", char: "기타", roman: "gita", meaning: "Guitar" },
    { id: "w_drawing", char: "그림", roman: "geurim", meaning: "Drawing / Picture" },
    { id: "w_like_verb", char: "좋아해요", roman: "joahaeyo", meaning: "Like (something)" },
    { id: "w_study_verb", char: "공부해요", roman: "gongbuhaeyo", meaning: "Study" },
    { id: "w_ask", char: "물어봐요", roman: "mureobwayo", meaning: "Ask" },
    { id: "w_answer", char: "대답해요", roman: "daedaphaeyo", meaning: "Answer" },
    { id: "w_help", char: "도와요", roman: "dowayo", meaning: "Help" },
    { id: "w_practice", char: "연습해요", roman: "yeonseuphaeyo", meaning: "Practice" },
    { id: "w_explain", char: "설명해요", roman: "seolmyeonghaeyo", meaning: "Explain" },
    { id: "w_show", char: "보여줘요", roman: "boyeojwoyo", meaning: "Show (me)" },
    { id: "w_fix", char: "고쳐요", roman: "gochyeoyo", meaning: "Fix / Repair" },
    { id: "w_choose", char: "선택해요", roman: "seontaekhaeyo", meaning: "Choose" },
    { id: "w_decide", char: "결정해요", roman: "gyeoljeonghaeyo", meaning: "Decide" },
    { id: "w_promise", char: "약속해요", roman: "yaksokhaeyo", meaning: "Promise" },
    { id: "w_boring", char: "재미없어요", roman: "jaemieopseoyo", meaning: "It's boring" },
    { id: "w_important", char: "중요해요", roman: "jungyohaeyo", meaning: "It's important" },
    { id: "w_special", char: "특별해요", roman: "teukbyeolhaeyo", meaning: "It's special" },
    { id: "w_weird", char: "이상해요", roman: "isanghaeyo", meaning: "It's weird" },
    { id: "w_amazing", char: "신기해요", roman: "singihaeyo", meaning: "It's amazing" },
    { id: "w_comfortable", char: "편해요", roman: "pyeonhaeyo", meaning: "It's comfortable" },
    { id: "w_uncomfortable", char: "불편해요", roman: "bulpyeonhaeyo", meaning: "It's uncomfortable" },
    { id: "w_dangerous", char: "위험해요", roman: "wiheomhaeyo", meaning: "It's dangerous" },
    { id: "w_safe", char: "안전해요", roman: "anjeonhaeyo", meaning: "It's safe" },
    { id: "w_slowly", char: "천천히", roman: "cheoncheonhi", meaning: "Slowly" },
    { id: "w_quickly", char: "빨리", roman: "ppalli", meaning: "Quickly" },
    { id: "w_a_little", char: "조금", roman: "jogeum", meaning: "A little" },
    { id: "w_a_lot_adv", char: "많이", roman: "mani", meaning: "A lot" },
    { id: "w_really", char: "정말", roman: "jeongmal", meaning: "Really" },
    { id: "w_yet", char: "아직", roman: "ajik", meaning: "Yet / Still" },
    { id: "w_already", char: "벌써", roman: "beolsseo", meaning: "Already" },
    { id: "w_again", char: "다시", roman: "dasi", meaning: "Again" },
    { id: "w_soon", char: "곧", roman: "got", meaning: "Soon" },
    { id: "w_usually", char: "보통", roman: "botong", meaning: "Usually" },
    { id: "w_relative", char: "친척", roman: "chincheok", meaning: "Relative" },
    { id: "w_twelve", char: "열둘", roman: "yeoldul", meaning: "Twelve" },
    { id: "w_thirty", char: "서른", roman: "seoreun", meaning: "Thirty" },
    { id: "w_thousand", char: "천", roman: "cheon", meaning: "Thousand" },
    { id: "w_waterfall", char: "폭포", roman: "pokpo", meaning: "Waterfall" },
    { id: "w_volcano", char: "화산", roman: "hwasan", meaning: "Volcano" },
    { id: "w_earthquake", char: "지진", roman: "jijin", meaning: "Earthquake" },
    { id: "w_rainbow", char: "무지개", roman: "mujigae", meaning: "Rainbow" },
    { id: "w_whale", char: "고래", roman: "gorae", meaning: "Whale" },
    { id: "w_shark", char: "상어", roman: "sangeo", meaning: "Shark" },
    { id: "w_giraffe", char: "기린", roman: "girin", meaning: "Giraffe" },
    { id: "w_camel", char: "낙타", roman: "nakta", meaning: "Camel" },
    { id: "w_app", char: "앱", roman: "aep", meaning: "App" },
    { id: "w_video", char: "동영상", roman: "dongyeongsang", meaning: "Video" },
    { id: "w_youtube", char: "유튜브", roman: "yutyubeu", meaning: "YouTube" },
    { id: "w_keyboard", char: "키보드", roman: "kibodeu", meaning: "Keyboard" },
    { id: "w_computer_mouse", char: "마우스", roman: "mauseu", meaning: "Computer mouse" },
    { id: "w_necktie", char: "넥타이", roman: "nektai", meaning: "Necktie" },
    { id: "w_ring", char: "반지", roman: "banji", meaning: "Ring" },
    { id: "w_scarf", char: "목도리", roman: "mokdori", meaning: "Scarf" },
    { id: "w_shower", char: "샤워", roman: "syawo", meaning: "Shower" },
    { id: "w_detergent", char: "세제", roman: "seje", meaning: "Detergent" },
    { id: "w_understand", char: "이해해요", roman: "ihaehaeyo", meaning: "I understand" },
    { id: "w_cheer_up", char: "힘내세요", roman: "himnaeseyo", meaning: "Cheer up" },
    { id: "w_wait_moment", char: "잠깐", roman: "jamkkan", meaning: "Wait a moment" },
    { id: "w_thanks_casual", char: "감사해요", roman: "gamsahaeyo", meaning: "Thank you (casual)" },
    { id: "w_mother_formal", char: "어머니", roman: "eomeoni", meaning: "Mother (formal)" },
    { id: "w_father_formal", char: "아버지", roman: "abeoji", meaning: "Father (formal)" },
    { id: "w_couple", char: "부부", roman: "bubu", meaning: "Married couple" },
    { id: "w_son_in_law", char: "사위", roman: "sawi", meaning: "Son-in-law" },
    { id: "w_daughter_in_law", char: "며느리", roman: "myeoneuri", meaning: "Daughter-in-law" },
    { id: "w_belly_button", char: "배꼽", roman: "baekkop", meaning: "Belly button" },
    { id: "w_toe", char: "발가락", roman: "balgaraq", meaning: "Toe" },
    { id: "w_forehead", char: "이마", roman: "ima", meaning: "Forehead" },
    { id: "w_eyelash", char: "속눈썹", roman: "songnunsseop", meaning: "Eyelash" },
    { id: "w_toenail", char: "발톱", roman: "baltop", meaning: "Toenail" },
    { id: "w_building", char: "건물", roman: "geonmul", meaning: "Building" },
    { id: "w_factory", char: "공장", roman: "gongjang", meaning: "Factory" },
    { id: "w_hallway", char: "복도", roman: "bokdo", meaning: "Hallway" },
    { id: "w_garden", char: "정원", roman: "jeongwon", meaning: "Garden" },
    { id: "w_valley", char: "계곡", roman: "gyegok", meaning: "Valley" },
    { id: "w_fire_truck", char: "소방차", roman: "sobangcha", meaning: "Fire truck" },
    { id: "w_ambulance", char: "구급차", roman: "gugeupcha", meaning: "Ambulance" },
    { id: "w_sidewalk", char: "보도", roman: "bodo", meaning: "Sidewalk" },
    { id: "w_public_bath", char: "목욕탕", roman: "mogyoktang", meaning: "Public bathhouse" },
    { id: "w_bookshelf", char: "책장", roman: "chaekjang", meaning: "Bookshelf" },
    { id: "w_flower_pot", char: "화분", roman: "hwabun", meaning: "Flower pot" },
    { id: "w_shelf", char: "선반", roman: "seonban", meaning: "Shelf" },
    { id: "w_hanger", char: "옷걸이", roman: "otgeori", meaning: "Clothes hanger" },
    { id: "w_iron", char: "다리미", roman: "darimi", meaning: "Clothes iron" },
    { id: "w_bean_sprouts", char: "콩나물", roman: "kongnamul", meaning: "Bean sprouts" },
    { id: "w_webfoot_octopus", char: "쭈꾸미", roman: "jjukkumi", meaning: "Webfoot octopus" },
    { id: "w_eel", char: "장어", roman: "jangeo", meaning: "Eel" },
    { id: "w_japchae", char: "잡채", roman: "japchae", meaning: "Japchae" },
    { id: "w_rice_cake_soup", char: "떡국", roman: "tteokguk", meaning: "Rice cake soup" },
    { id: "w_red_bean", char: "팥", roman: "pat", meaning: "Red bean" },
    { id: "w_bossam", char: "보쌈", roman: "bossam", meaning: "Bossam (boiled pork wraps)" },
    { id: "w_sundae", char: "순대", roman: "sundae", meaning: "Korean blood sausage" },
    { id: "w_fish_cake", char: "어묵", roman: "eomuk", meaning: "Fish cake" },
    { id: "w_pork_cutlet", char: "돈까스", roman: "donkkaseu", meaning: "Pork cutlet" },
    { id: "w_makgeolli", char: "막걸리", roman: "makgeolli", meaning: "Makgeolli (rice wine)" },
    { id: "w_soju", char: "소주", roman: "soju", meaning: "Soju" },
    { id: "w_panda", char: "판다", roman: "panda", meaning: "Panda" },
    { id: "w_crocodile", char: "악어", roman: "ageo", meaning: "Crocodile" },
    { id: "w_hedgehog", char: "고슴도치", roman: "goseumdochi", meaning: "Hedgehog" },
    { id: "w_pigeon", char: "비둘기", roman: "bidulgi", meaning: "Pigeon" },
    { id: "w_sparrow", char: "참새", roman: "chamsae", meaning: "Sparrow" },
    { id: "w_mole", char: "두더지", roman: "dudeoji", meaning: "Mole" },
    { id: "w_koala", char: "코알라", roman: "koalla", meaning: "Koala" },
    { id: "w_accountant", char: "회계사", roman: "hoegyesa", meaning: "Accountant" },
    { id: "w_pharmacist", char: "약사", roman: "yaksa", meaning: "Pharmacist" },
    { id: "w_architect", char: "건축가", roman: "geonchukga", meaning: "Architect" },
    { id: "w_scientist", char: "과학자", roman: "gwahakja", meaning: "Scientist" },
    { id: "w_hairdresser", char: "미용사", roman: "miyongsa", meaning: "Hairdresser" },
    { id: "w_photographer", char: "사진사", roman: "sajinsa", meaning: "Photographer" },
    { id: "w_embarrassed", char: "부끄러워요", roman: "bukkeureowoyo", meaning: "I'm embarrassed" },
    { id: "w_excited", char: "설레요", roman: "seolleyo", meaning: "I'm excited" },
    { id: "w_annoyed", char: "짜증나요", roman: "jjajeungnayo", meaning: "I'm annoyed" },
    { id: "w_anxious", char: "불안해요", roman: "buranhaeyo", meaning: "I'm anxious" },
    { id: "w_surprised", char: "놀라워요", roman: "nollawoyo", meaning: "It's surprising" },
    { id: "w_turn_on", char: "켜요", roman: "kyeoyo", meaning: "Turn on" },
    { id: "w_turn_off", char: "꺼요", roman: "kkeoyo", meaning: "Turn off" },
    { id: "w_throw", char: "던져요", roman: "deonjyeoyo", meaning: "Throw" },
    { id: "w_catch", char: "잡아요", roman: "jabayo", meaning: "Catch" },
    { id: "w_hide", char: "숨겨요", roman: "sumgyeoyo", meaning: "Hide" },
    { id: "w_wake_someone", char: "깨워요", roman: "kkaewoyo", meaning: "Wake (someone) up" },
    { id: "w_confirm", char: "확인해요", roman: "hwaginhaeyo", meaning: "Confirm / Check" },
    { id: "w_try", char: "시도해요", roman: "sidohaeyo", meaning: "Try" },
    { id: "w_arrive", char: "도착해요", roman: "dochakhaeyo", meaning: "Arrive" },
    { id: "w_depart", char: "출발해요", roman: "chulbalhaeyo", meaning: "Depart" },
    { id: "w_visit", char: "방문해요", roman: "bangmunhaeyo", meaning: "Visit" },
    { id: "w_spicy", char: "매워요", roman: "maewoyo", meaning: "It's spicy" },
    { id: "w_sweet", char: "달콤해요", roman: "dalkomhaeyo", meaning: "It's sweet" },
    { id: "w_salty", char: "짜요", roman: "jjayo", meaning: "It's salty" },
    { id: "w_wide", char: "넓어요", roman: "neolbeoyo", meaning: "It's wide" },
    { id: "w_narrow", char: "좁아요", roman: "jobayo", meaning: "It's narrow" },
    { id: "w_suddenly", char: "갑자기", roman: "gapjagi", meaning: "Suddenly" },
    { id: "w_continuously", char: "계속", roman: "gyesok", meaning: "Continuously / Keep" },
    { id: "w_of_course", char: "물론", roman: "mullon", meaning: "Of course" },
    { id: "w_almost", char: "거의", roman: "geoui", meaning: "Almost" },
    { id: "w_especially", char: "특히", roman: "teukhi", meaning: "Especially" },
    { id: "w_finally", char: "드디어", roman: "deudieo", meaning: "Finally" },
    { id: "w_thirteen", char: "열셋", roman: "yeolset", meaning: "Thirteen" },
    { id: "w_forty", char: "마흔", roman: "maheun", meaning: "Forty" },
    { id: "w_ten_thousand", char: "만", roman: "man", meaning: "Ten thousand" },
    { id: "w_sunrise", char: "일출", roman: "ilchul", meaning: "Sunrise" },
    { id: "w_sunset", char: "석양", roman: "seogyang", meaning: "Sunset" },
    { id: "w_hail", char: "우박", roman: "ubak", meaning: "Hail" },
    { id: "w_shower_rain", char: "소나기", roman: "sonagi", meaning: "Rain shower" },
    { id: "w_delivery", char: "택배", roman: "taekbae", meaning: "Parcel delivery" },
    { id: "w_receipt", char: "영수증", roman: "yeongsujeung", meaning: "Receipt" },
    { id: "w_discount", char: "할인", roman: "harin", meaning: "Discount" },
    { id: "w_cash", char: "현금", roman: "hyeongeum", meaning: "Cash" },
    { id: "w_card", char: "카드", roman: "kadeu", meaning: "Card" },
    { id: "w_coin", char: "동전", roman: "dongjeon", meaning: "Coin" },
    { id: "w_marathon", char: "마라톤", roman: "maraton", meaning: "Marathon" },
    { id: "w_ski", char: "스키", roman: "seuki", meaning: "Ski / Skiing" },
    { id: "w_volleyball", char: "배구", roman: "baegu", meaning: "Volleyball" },
    { id: "w_bowling", char: "볼링", roman: "bolling", meaning: "Bowling" },
    { id: "w_jump_rope", char: "줄넘기", roman: "jullneomgi", meaning: "Jump rope" },
    { id: "w_gym_workout", char: "헬스", roman: "helseu", meaning: "Gym workout" },
    { id: "w_helmet", char: "헬멧", roman: "helmet", meaning: "Helmet" },
    { id: "w_victory", char: "승리", roman: "seungri", meaning: "Victory" },
    { id: "w_defeat", char: "패배", roman: "paebae", meaning: "Defeat" },
    { id: "w_praise", char: "칭찬", roman: "chingchan", meaning: "Praise / Compliment" },
    { id: "w_cheer", char: "응원", roman: "eungwon", meaning: "Cheer / Support" },
    { id: "w_mother_in_law", char: "시어머니", roman: "sieomeoni", meaning: "Mother-in-law" },
    { id: "w_father_in_law", char: "장인", roman: "jangin", meaning: "Father-in-law" },
    { id: "w_paternal_aunt", char: "고모", roman: "gomo", meaning: "Paternal aunt" },
    { id: "w_wife_brother", char: "처남", roman: "cheonam", meaning: "Wife's brother" },
    { id: "w_nostril", char: "콧구멍", roman: "kotgumeong", meaning: "Nostril" },
    { id: "w_liver", char: "간", roman: "gan", meaning: "Liver" },
    { id: "w_tears", char: "눈물", roman: "nummul", meaning: "Tears" },
    { id: "w_saliva", char: "침", roman: "chim", meaning: "Saliva" },
    { id: "w_sweat", char: "땀", roman: "ttam", meaning: "Sweat" },
    { id: "w_brain", char: "뇌", roman: "noe", meaning: "Brain" },
    { id: "w_amusement_park", char: "놀이공원", roman: "noligongwon", meaning: "Amusement park" },
    { id: "w_campsite", char: "캠핑장", roman: "kaempingjang", meaning: "Campsite" },
    { id: "w_rest_area", char: "휴게소", roman: "hyugeso", meaning: "Highway rest area" },
    { id: "w_planet", char: "행성", roman: "haengseong", meaning: "Planet" },
    { id: "w_soft_tofu", char: "순두부", roman: "sundubu", meaning: "Soft tofu" },
    { id: "w_samgyetang", char: "삼계탕", roman: "samgyetang", meaning: "Ginseng chicken soup" },
    { id: "w_kimchi_stew", char: "김치찌개", roman: "gimchijjigae", meaning: "Kimchi stew" },
    { id: "w_hotteok", char: "호떡", roman: "hotteok", meaning: "Hotteok (sweet pancake)" },
    { id: "w_fish_shaped_bread", char: "붕어빵", roman: "bungeoppang", meaning: "Fish-shaped bread" },
    { id: "w_sikhye", char: "식혜", roman: "sikhye", meaning: "Sikhye (sweet rice drink)" },
    { id: "w_red_pepper_powder", char: "고춧가루", roman: "gochutgaru", meaning: "Red pepper powder" },
    { id: "w_sesame_oil", char: "참기름", roman: "chamgireum", meaning: "Sesame oil" },
    { id: "w_hippo", char: "하마", roman: "hama", meaning: "Hippo" },
    { id: "w_rhino", char: "코뿔소", roman: "koppulso", meaning: "Rhino" },
    { id: "w_kangaroo", char: "캥거루", roman: "kaenggeoru", meaning: "Kangaroo" },
    { id: "w_cheetah", char: "치타", roman: "chita", meaning: "Cheetah" },
    { id: "w_raccoon", char: "너구리", roman: "neoguri", meaning: "Raccoon dog" },
    { id: "w_swan", char: "백조", roman: "baekjo", meaning: "Swan" },
    { id: "w_designer", char: "디자이너", roman: "dijaineo", meaning: "Designer" },
    { id: "w_programmer", char: "프로그래머", roman: "peurogeuraemeo", meaning: "Programmer" },
    { id: "w_interpreter", char: "통역사", roman: "tongyeoksa", meaning: "Interpreter" },
    { id: "w_delivery_person", char: "배달원", roman: "baedalwon", meaning: "Delivery person" },
    { id: "w_follow", char: "따라가요", roman: "ttaragayo", meaning: "Follow" },
    { id: "w_follow_me", char: "따라와요", roman: "ttarawayo", meaning: "Follow me" },
    { id: "w_put_down", char: "놓아요", roman: "noayo", meaning: "Put down" },
    { id: "w_put_in", char: "넣어요", roman: "neoyo", meaning: "Put in" },
    { id: "w_take_out", char: "빼요", roman: "ppaeyo", meaning: "Take out" },
    { id: "w_put_away", char: "치워요", roman: "chiwoyo", meaning: "Put away / Tidy up" },
    { id: "w_take_photo", char: "찍어요", roman: "jjigeoyo", meaning: "Take (a photo)" },
    { id: "w_recommend", char: "추천해요", roman: "chucheonhaeyo", meaning: "Recommend" },
    { id: "w_reserve", char: "예약해요", roman: "yeyakhaeyo", meaning: "Reserve / Book" },
    { id: "w_cancel", char: "취소해요", roman: "chwisohaeyo", meaning: "Cancel" },
    { id: "w_exchange", char: "교환해요", roman: "gyohwanhaeyo", meaning: "Exchange" },
    { id: "w_apologize", char: "사과해요", roman: "sagwahaeyo", meaning: "Apologize" },
    { id: "w_worry", char: "걱정해요", roman: "geokjeonghaeyo", meaning: "Worry" },
    { id: "w_soft", char: "부드러워요", roman: "budeureowoyo", meaning: "It's soft" },
    { id: "w_hard", char: "딱딱해요", roman: "ttakttakhaeyo", meaning: "It's hard / stiff" },
    { id: "w_slippery", char: "미끄러워요", roman: "mikkeureowoyo", meaning: "It's slippery" },
    { id: "w_fresh", char: "신선해요", roman: "sinseonhaeyo", meaning: "It's fresh" },
    { id: "w_kind", char: "친절해요", roman: "chinjeolhaeyo", meaning: "It's kind" },
    { id: "w_diligent", char: "부지런해요", roman: "bujireonhaeyo", meaning: "I'm diligent" },
    { id: "w_lazy", char: "게을러요", roman: "geeulleoyo", meaning: "I'm lazy" },
    { id: "w_each_other", char: "서로", roman: "seoro", meaning: "Each other" },
    { id: "w_never", char: "절대", roman: "jeoldae", meaning: "Never / Absolutely not" },
    { id: "w_definitely", char: "꼭", roman: "kkok", meaning: "Definitely / Must" },
    { id: "w_by_chance", char: "혹시", roman: "hoksi", meaning: "By any chance" },
    { id: "w_maybe", char: "아마", roman: "ama", meaning: "Maybe / Probably" },
    { id: "w_bluetooth", char: "블루투스", roman: "beullutuseu", meaning: "Bluetooth" },
    { id: "w_monitor", char: "모니터", roman: "moniteo", meaning: "Monitor" },
    { id: "w_speaker", char: "스피커", roman: "seupikeo", meaning: "Speaker" },
    { id: "w_share", char: "공유", roman: "gongyu", meaning: "Share" },
    { id: "w_graduation", char: "졸업", roman: "joreop", meaning: "Graduation" },
    { id: "w_school_vacation", char: "방학", roman: "banghak", meaning: "School vacation" },
    { id: "w_sunglasses", char: "선글라스", roman: "seungeullaseu", meaning: "Sunglasses" },
    { id: "w_dress_shoes", char: "구두", roman: "gudu", meaning: "Dress shoes" },
    { id: "w_jeans", char: "청바지", roman: "cheongbaji", meaning: "Jeans" },
    { id: "w_hoodie", char: "후드티", roman: "hudeuti", meaning: "Hoodie" },
    { id: "w_dew", char: "이슬", roman: "iseul", meaning: "Dew" },
    { id: "w_yellow_dust", char: "황사", roman: "hwangsa", meaning: "Yellow dust" },
    { id: "w_flood", char: "홍수", roman: "hongsu", meaning: "Flood" },
    { id: "w_table_tennis", char: "탁구", roman: "takgu", meaning: "Table tennis" },
    { id: "w_taekwondo", char: "태권도", roman: "taekwondo", meaning: "Taekwondo" },
    { id: "w_yoga", char: "요가", roman: "yoga", meaning: "Yoga" },
    { id: "w_fourteen", char: "열넷", roman: "yeolnet", meaning: "Fourteen" },
    { id: "w_fifty", char: "오십", roman: "osip", meaning: "Fifty" },
    { id: "w_cold_illness", char: "감기", roman: "gamgi", meaning: "Cold (illness)" },
    { id: "w_body_temperature", char: "체온", roman: "cheon", meaning: "Body temperature" },
    { id: "w_cough", char: "기침", roman: "gichim", meaning: "Cough" },
    { id: "w_headache", char: "두통", roman: "dutong", meaning: "Headache" },
    { id: "w_injection", char: "주사", roman: "jusa", meaning: "Injection / Shot" },
    { id: "w_bathtub", char: "욕조", roman: "yokjo", meaning: "Bathtub" },
    { id: "w_entrance", char: "현관", roman: "hyeongwan", meaning: "Entrance / Front door" },
    { id: "w_balcony", char: "발코니", roman: "balkoni", meaning: "Balcony" },
    { id: "w_drum", char: "드럼", roman: "deureom", meaning: "Drum" },
    { id: "w_violin", char: "바이올린", roman: "baiollin", meaning: "Violin" },
    { id: "w_art", char: "미술", roman: "misul", meaning: "Art" },
    { id: "w_shuttle_bus", char: "셔틀버스", roman: "syeoteulbeoseu", meaning: "Shuttle bus" },
    { id: "w_train_ticket", char: "승차권", roman: "seungchagwon", meaning: "Train ticket" },
    { id: "w_jeyuk_bokkeum", char: "제육볶음", roman: "jeyukbokkeum", meaning: "Spicy stir-fried pork" },
    { id: "w_makguksu", char: "막국수", roman: "makguksu", meaning: "Buckwheat noodles" },
    { id: "w_badger", char: "오소리", roman: "osori", meaning: "Badger" },
    { id: "w_mailbox", char: "우체통", roman: "uchettong", meaning: "Mailbox" },
    { id: "w_fallen_leaves", char: "낙엽", roman: "nagyeop", meaning: "Fallen leaves" },
    { id: "w_sprout", char: "새싹", roman: "saessak", meaning: "Sprout / Seedling" },
    { id: "w_nest", char: "둥지", roman: "dungji", meaning: "Nest" },
    { id: "w_animal_egg", char: "알", roman: "al", meaning: "Egg (animal)" },
    { id: "w_copy", char: "복사해요", roman: "boksahaeyo", meaning: "Copy" },
    { id: "w_repeat", char: "반복해요", roman: "banbokhaeyo", meaning: "Repeat" },
    { id: "w_compare", char: "비교해요", roman: "bigyohaeyo", meaning: "Compare" },
    { id: "w_dry", char: "건조해요", roman: "geonjohaeyo", meaning: "It's dry" },
    { id: "w_husbands_father", char: "시아버지", roman: "siabeoji", meaning: "Father-in-law (husband's side)" },
    { id: "w_wife_mother", char: "장모", roman: "jangmo", meaning: "Mother-in-law (wife's side)" },
    { id: "w_wife_sister", char: "처제", roman: "cheoje", meaning: "Wife's younger sister" },
    { id: "w_lung", char: "폐", roman: "pye", meaning: "Lung" },
    { id: "w_kidney", char: "신장", roman: "sinjang", meaning: "Kidney" },
    { id: "w_stomach_organ", char: "위", roman: "wi", meaning: "Stomach (organ)" },
    { id: "w_muscle", char: "근육", roman: "geunyuk", meaning: "Muscle" },
    { id: "w_joint", char: "관절", roman: "gwanjeol", meaning: "Joint" },
    { id: "w_voice", char: "목소리", roman: "moksori", meaning: "Voice" },
    { id: "w_breath", char: "숨", roman: "sum", meaning: "Breath" },
    { id: "w_aquarium", char: "수족관", roman: "sujokgwan", meaning: "Aquarium" },
    { id: "w_cathedral", char: "성당", roman: "seongdang", meaning: "Cathedral" },
    { id: "w_buddhist_temple", char: "사찰", roman: "sachal", meaning: "Buddhist temple" },
    { id: "w_ski_resort", char: "스키장", roman: "seukijang", meaning: "Ski resort" },
    { id: "w_doenjang_stew", char: "된장찌개", roman: "doenjangjjigae", meaning: "Soybean paste stew" },
    { id: "w_gamjatang", char: "감자탕", roman: "gamjatang", meaning: "Pork backbone stew" },
    { id: "w_army_stew", char: "부대찌개", roman: "budaejjigae", meaning: "Army stew" },
    { id: "w_sashimi", char: "회", roman: "hoe", meaning: "Sashimi / Raw fish" },
    { id: "w_patbingsu", char: "팥빙수", roman: "patbingsu", meaning: "Shaved ice with red beans" },
    { id: "w_green_tea", char: "녹차", roman: "nokcha", meaning: "Green tea" },
    { id: "w_porridge", char: "죽", roman: "juk", meaning: "Porridge" },
    { id: "w_leopard", char: "표범", roman: "pyobeom", meaning: "Leopard" },
    { id: "w_alpaca", char: "알파카", roman: "alpaka", meaning: "Alpaca" },
    { id: "w_zebra", char: "얼룩말", roman: "eollungmal", meaning: "Zebra" },
    { id: "w_crayfish", char: "가재", roman: "gajae", meaning: "Crayfish" },
    { id: "w_toad", char: "두꺼비", roman: "dukkeobi", meaning: "Toad" },
    { id: "w_owl", char: "올빼미", roman: "olppaemi", meaning: "Owl" },
    { id: "w_magpie", char: "까치", roman: "kkachi", meaning: "Magpie" },
    { id: "w_engineer", char: "엔지니어", roman: "enjinieo", meaning: "Engineer" },
    { id: "w_salesperson", char: "판매원", roman: "panmaewon", meaning: "Salesperson" },
    { id: "w_lift_up", char: "올려요", roman: "ollyeoyo", meaning: "Lift up / Raise" },
    { id: "w_lower", char: "내려요", roman: "naeryeoyo", meaning: "Lower / Put down" },
    { id: "w_attach", char: "붙여요", roman: "butyeoyo", meaning: "Attach / Stick" },
    { id: "w_remove", char: "떼요", roman: "tteyo", meaning: "Remove / Peel off" },
    { id: "w_fold", char: "접어요", roman: "jeobeoyo", meaning: "Fold" },
    { id: "w_unfold", char: "펴요", roman: "pyeoyo", meaning: "Spread / Unfold" },
    { id: "w_hug", char: "안아요", roman: "anayo", meaning: "Hug" },
    { id: "w_cover", char: "덮어요", roman: "deopeoyo", meaning: "Cover" },
    { id: "w_wrap", char: "감싸요", roman: "gamssayo", meaning: "Wrap" },
    { id: "w_shake", char: "흔들어요", roman: "heundeureoyo", meaning: "Shake" },
    { id: "w_apply", char: "신청해요", roman: "sincheonghaeyo", meaning: "Apply" },
    { id: "w_save", char: "저장해요", roman: "jeojanghaeyo", meaning: "Save" },
    { id: "w_delete", char: "삭제해요", roman: "sakjehaeyo", meaning: "Delete" },
    { id: "w_search", char: "검색해요", roman: "geomsaekhaeyo", meaning: "Search" },
    { id: "w_translate", char: "번역해요", roman: "beonyeokhaeyo", meaning: "Translate" },
    { id: "w_record_audio", char: "녹음해요", roman: "nogeumhaeyo", meaning: "Record (audio)" },
    { id: "w_honest", char: "정직해요", roman: "jeongjikhaeyo", meaning: "I'm honest" },
    { id: "w_frank", char: "솔직해요", roman: "soljikhaeyo", meaning: "I'm frank" },
    { id: "w_humble", char: "겸손해요", roman: "gyeomsonhaeyo", meaning: "I'm humble" },
    { id: "w_unkind", char: "불친절해요", roman: "bulchinjeolhaeyo", meaning: "It's unkind" },
    { id: "w_lonely", char: "외로워요", roman: "oerowoyo", meaning: "I'm lonely" },
    { id: "w_miss_someone", char: "그리워요", roman: "geuriwoyo", meaning: "I miss (someone)" },
    { id: "w_satisfied", char: "만족해요", roman: "manjokhaeyo", meaning: "I'm satisfied" },
    { id: "w_disappointed", char: "실망해요", roman: "silmanghaeyo", meaning: "I'm disappointed" },
    { id: "w_really_adv", char: "진짜", roman: "jinjja", meaning: "Really / Truly" },
    { id: "w_very", char: "아주", roman: "aju", meaning: "Very" },
    { id: "w_already_adv", char: "이미", roman: "imi", meaning: "Already" },
    { id: "w_again_adv", char: "또", roman: "tto", meaning: "Again / Also" },
    { id: "w_rather", char: "오히려", roman: "ohiryeo", meaning: "Rather / Instead" },
    { id: "w_no_way", char: "설마", roman: "seolma", meaning: "No way / Surely not" },
    { id: "w_hurry", char: "서둘러", roman: "seodulleo", meaning: "Hurry" },
    { id: "w_printer", char: "프린터", roman: "peurinteo", meaning: "Printer" },
    { id: "w_comment", char: "댓글", roman: "daetgeul", meaning: "Comment" },
    { id: "w_subscribe", char: "구독", roman: "gudok", meaning: "Subscribe" },
    { id: "w_notification", char: "알림", roman: "allim", meaning: "Notification" },
    { id: "w_password", char: "비밀번호", roman: "bimilbeonho", meaning: "Password" },
    { id: "w_enrollment", char: "입학", roman: "iphak", meaning: "Enrollment" },
    { id: "w_school_club", char: "동아리", roman: "dongari", meaning: "School club" },
    { id: "w_jacket", char: "재킷", roman: "jaekit", meaning: "Jacket" },
    { id: "w_sweater", char: "스웨터", roman: "seuweteo", meaning: "Sweater" },
    { id: "w_slippers", char: "슬리퍼", roman: "seullipeo", meaning: "Slippers" },
    { id: "w_necklace", char: "목걸이", roman: "mokgeori", meaning: "Necklace" },
    { id: "w_belt", char: "벨트", roman: "belteu", meaning: "Belt" },
    { id: "w_field", char: "들판", roman: "deulpan", meaning: "Field / Meadow" },
    { id: "w_full_moon", char: "보름달", roman: "boreumdal", meaning: "Full moon" },
    { id: "w_frost", char: "서리", roman: "seori", meaning: "Frost" },
    { id: "w_fine_dust", char: "미세먼지", roman: "misemeonji", meaning: "Fine dust" },
    { id: "w_drought", char: "가뭄", roman: "gamum", meaning: "Drought" },
    { id: "w_treatment", char: "치료", roman: "chiryo", meaning: "Treatment" },
    { id: "w_surgery", char: "수술", roman: "susul", meaning: "Surgery" },
    { id: "w_bandaid", char: "반창고", roman: "banchanggo", meaning: "Band-aid" },
    { id: "w_wound", char: "상처", roman: "sangcheo", meaning: "Wound / Injury" },
    { id: "w_bruise", char: "멍", roman: "meong", meaning: "Bruise" },
    { id: "w_outlet", char: "콘센트", roman: "konsenteu", meaning: "Power outlet" },
    { id: "w_veranda", char: "베란다", roman: "beranda", meaning: "Veranda" },
    { id: "w_kendo", char: "검도", roman: "geomdo", meaning: "Kendo" },
    { id: "w_judo", char: "유도", roman: "yudo", meaning: "Judo" },
    { id: "w_pilates", char: "필라테스", roman: "pillateseu", meaning: "Pilates" },
    { id: "w_saxophone", char: "색소폰", roman: "saeksopon", meaning: "Saxophone" },
    { id: "w_express_bus", char: "고속버스", roman: "gosokbeoseu", meaning: "Express bus" },
    { id: "w_electric_scooter", char: "전동킥보드", roman: "jeondongkikbodeu", meaning: "Electric scooter" },
    { id: "w_fifteen", char: "열다섯", roman: "yeoldaseot", meaning: "Fifteen" },
    { id: "w_twenty_one", char: "스물하나", roman: "seumulhana", meaning: "Twenty-one" },
    { id: "w_sixty", char: "육십", roman: "yukship", meaning: "Sixty" },
    { id: "w_responsibility", char: "책임", roman: "chaegim", meaning: "Responsibility" },
    { id: "w_promise_noun", char: "약속", roman: "yaksok", meaning: "Promise / Appointment" },
    { id: "w_understood_formal", char: "알겠습니다", roman: "algetseumnida", meaning: "I understand (formal)" },
    { id: "w_miss_you", char: "보고 싶어요", roman: "bogo sipeoyo", meaning: "I miss you" },
    { id: "w_take_care", char: "잘 지내요", roman: "jal jinaeyo", meaning: "Take care / I'm doing well" },
    { id: "w_not_sure", char: "모르겠어요", roman: "moreugeseyo", meaning: "I'm not sure" },
  ],

  _allSyllablesCache: null,
  _syllablesGroupedCache: null,

  getAllSyllables() {
    if (!this._allSyllablesCache) {
      this._allSyllablesCache = buildAllSyllables(
        this.consonants,
        this.vowels,
        this.compound_vowels,
      );
    }
    return this._allSyllablesCache;
  },

  getSyllablesGroupedByConsonant() {
    if (!this._syllablesGroupedCache) {
      this._syllablesGroupedCache = buildSyllablesGroupedByConsonant(
        this.consonants,
        this.vowels,
        this.compound_vowels,
      );
    }
    return this._syllablesGroupedCache;
  },

  get syllables() {
    return this.getAllSyllables();
  },

  stages: [
    {
      id: 1,
      title: "Consonants I",
      type: "consonant",
      items: () => HangulData.consonants.slice(0, 7),
    },
    {
      id: 2,
      title: "Consonants II",
      type: "consonant",
      items: () => HangulData.consonants.slice(7),
    },
    { id: 3, title: "Vowels", type: "vowel", items: () => HangulData.vowels },
    {
      id: 4,
      title: "Syllables",
      type: "syllable",
      items: () => HangulData.syllables.slice(0, 10),
    },
    {
      id: 5,
      title: "Words I",
      type: "word",
      items: () => HangulData.words.slice(0, 8),
    },
    {
      id: 6,
      title: "Words II",
      type: "word",
      items: () => HangulData.words.slice(8),
    },
    {
      id: 7,
      title: "Stroke Writing",
      type: "stroke",
      items: () => HangulData.syllables.slice(0, 5),
    },
    {
      id: 8,
      title: "Final Quiz",
      type: "quiz",
      items: () => [...HangulData.syllables, ...HangulData.words.slice(0, 5)],
    },
  ],

  /** TTS text: consonants use letter names (기역), vowels use sounds (아), words as written. */
  getSpeakText(itemOrChar) {
    if (!itemOrChar) return "";
    if (typeof itemOrChar === "string") {
      return JAMO_SPEAK[itemOrChar] || itemOrChar;
    }
    if (itemOrChar.speak) return itemOrChar.speak;
    const ch = itemOrChar.char || "";
    if (!ch) return "";
    if (itemOrChar.meaning) return ch;
    return JAMO_SPEAK[ch] || ch;
  },

  getLabel(item) {
    if (!item) return "";
    if (item.meaning) return item.meaning;
    if (item.sound) return item.sound;
    return item.roman || item.char;
  },

  getHint(item) {
    if (!item) return "";
    if (item.meaning) return `${item.roman} \u00B7 ${item.meaning}`;
    if (item.sound) return `${item.roman} \u00B7 ${item.sound}`;
    return item.roman || "";
  },

  getStage(id) {
    const stage = HangulData.stages.find((s) => s.id === Number(id));
    if (!stage)
      return { ...HangulData.stages[0], items: HangulData.stages[0].items() };
    return { ...stage, items: stage.items() };
  },

  getRandomQuizOptions(correct, pool, count = 4) {
    const others = pool.filter((item) => item.char !== correct.char);
    const shuffled = [...others].sort(() => Math.random() - 0.5);
    const options = [correct, ...shuffled.slice(0, count - 1)];
    return options.sort(() => Math.random() - 0.5);
  },

  starsFromScore(score, maxScore) {
    const ratio = maxScore > 0 ? score / maxScore : 0;
    if (ratio >= 0.9) return 3;
    if (ratio >= 0.6) return 2;
    if (ratio >= 0.3) return 1;
    return 0;
  },
};

if (typeof module !== "undefined") module.exports = HangulData;
